### ISSUE TITLE
Audio Player Default

### ISSUE THREAD

**Issue by scarysnow** [pock/pock#104]
Despite having Spotify open by default and iTunes closed, Pock seems to default to iTunes as the audio player by default upon launch. 

This requires some tinkering where I have to close iTunes (if launched from Pock), close Spotify, reopen Spotify, and then reapply the audio player to the touchbar so it recognizes Spotify.

It would be preferable if Pock recognized the audio player of choice, or offered a way to select a default to use.

**Comment by dudz2888** [comment]
Came here to report the same thing.

**Comment by eorsinijr** [comment]
I'm unable to get it to switch to spotify at all.  It stays on iTunes for me.  I never use iTunes, only Spotify

**Comment by L1cardo** [comment]
You may want to have a look a this! #324
