### ISSUE TITLE
Option to alter Spotify gestures

### ISSUE THREAD

**Issue by rapkyt** [pock/pock#107]
**Is your feature request related to a problem? Please describe.**
In my mind,  the actions applied to the "Now Playing" widget: "swipe right" and "swipe left" are upside down. So when I want to skip the current song, I end up going to the beginning of the current one and then I realize that I have to swipe to the right.

**Describe the solution you'd like**
I would like a checkbox to alter the gestures, if you alter them, "swipe right" will be bound to "previous song" action and "swipe left" to "next song".

**Describe alternatives you've considered**
I didn't think about an alternative to the described solution that I'd like.
:grimacing:

**Additional context**
I like more the idea of swiping through the widget than have any buttons.

**Comment by jayhxmo** [comment]
Does the swipe gestures work for you? They do not for me :(

**Comment by rapkyt** [comment]
They do work for me, but the swipe gesture is a little bit tricky, you have to get used to it.

You have to tap and swipe within the widget, if your finger "cross" to another widget, the gesture will not work, that said, the swipe gesture is like the tap gesture, only that you have to move your finger just a little bit.

**Comment by stanislasdrg** [comment]
I second this request. The Spotify gesture does not feel natural, especially since in all apps and no matter the content, swipe is done in the reverse direction: Swipe left for next, right for previous.

**Comment by rapkyt** [comment]
After five months I got used to the gestures default behavior, no longer face the problem described in the issue (when I want to skip the current song, I end up going to the beginning of the current one and then I realize that I have to swipe to the right)

Buuuuuut,  I still would want to be able to alter the swipe directions

**Comment by JesusLeon** [comment]
I would like to put emphasis in this request, as the standard way in the Apple environment (and touch GUI's overall) is to mimic natural gestures. So swiping from left to right (o-->) should trigger a "back" action; and swiping right to left (<--o) should trigger a "next" action. At this point it feels counterintuitive for me to gesture in the current configuration. 

Alternatively, this could be a simple configuration option, like a checkbox to reverse gestures, in this way, is the user who decides which way feels more natural. 

Thank you. 
So far, loving the app! ⭐️ ⭐️ ⭐️ ⭐️ ⭐️  And can't wait for the open dev part.

**Comment by Rijk** [comment]
They are SO the wrong way around! 😅 A total mindf*ck every time, even if I _try_ to reverse it in my head I still do it wrong haha
