### ISSUE TITLE
MS Teams Icon Constantly Bouncing

### ISSUE THREAD

**Issue by tdudz-ui** [pock/pock#108]
Even though I'm not recieving notifications in MS Teams, the icon bounces constantly. If I go to teams, the icon stops bouncing for a minute or two and then starts back.

**Comment by DefCon-007** [comment]
I faced similar kind of issue with Chrome too.

**Comment by TheBrickster** [comment]
I'm having the same issue with MS Teams, but also the icon is not showing as expected, I get this icon instead: 

![icon](https://user-images.githubusercontent.com/3429696/60171856-5d59c980-9803-11e9-87d0-58d6ef7960db.jpg)

**Comment by TheBrickster** [comment]
Also touching the icon doesn't bring up MS Teams

**Comment by rcampbell22** [comment]
v0.5.2 - I'm having the same issue with the bouncing but clicking it does bring the window to focus, and it's the correct icon.

More of a query/observation than issue is that Outlook has the notification badge appearing when it is also showing in the task bar, but Teams doesn't.

**Comment by lespaul1488** [comment]
Check the resolution from this comment could help with icon bounces 
 https://github.com/pigigaldi/Pock/issues/20#issuecomment-505349154

**Comment by nova0052** [comment]
I'm seeing this on 0.5.3

MS Teams icon bounces until I give the app focus, then stops for a short time. Usually starts bouncing again in less than an hour.

I followed the instructions shared in lespaul1488's comment above; did not resolve the bouncing issue and caused the icon to be replaced with a generic page icon.

**Comment by shanep2300** [comment]
@lespaul1488 That fix is for the changing the icon to the default Teams one. No fix for the bouncing or being able to open Teams.
