### ISSUE TITLE
Ability to display custom icons?

### ISSUE THREAD

**Issue by SCasarotto** [pock/pock#11]
First off, this is super awesome and I appreciate your work on this.

I just installed the program and noticed I wasn't seeing my custom icons in the touch bar. Is this something that could be added? No big deal if not just wanted to throw it out there.

![image](https://user-images.githubusercontent.com/13336976/54883927-ed6d2900-4e38-11e9-8d2b-beba724cf136.png)

**Comment by tsengvn** [comment]
up for this too, wish pock can show my custom folder icon

**Comment by debivort** [comment]
I would like this too. Thanks for the great app though!

**Comment by Mgt-A** [comment]
Hi ! I'd love that too, I have several folder in my dock and even if I know their order, I wish I could use my custom icons in Pock to recognize them :).
