### ISSUE TITLE
Apps which run in menu bar and Dock won‘t show up in Pock

### ISSUE THREAD

**Issue by iDjay** [pock/pock#114]
Every app which runs (app icon) in menu bar and dock are not available in Pock.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pigigaldi** [comment]
Could you please name one of these apps, so I can try to replicate this situation?

**Comment by iDjay** [comment]
>Could you please name one of these apps, so I can try to replicate this situation?

@pigigaldi MacUpdater f.e.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
