### ISSUE TITLE
add an option to show open apps first

### ISSUE THREAD

**Issue by bmurphy1976** [pock/pock#115]
It would be great if there was an option to sort the apps so that open apps show up at the front of the list.  I have my dock organized by application type, and I usually have one of each type of app open at a time.  In the regular dock it's not an issue because the whole dock is visible on the screen.  In pock I have to scroll to see the overflowed apps.  

Not a big deal, but would make the app even more useful!

**Comment by pigigaldi** [comment]
Something like `ctrl+tab`?

**Comment by bmurphy1976** [comment]
Not sure what you mean by ctlr+tab in this case...  My current layout is:

browsers, email, chat apps, terminal, editors, etc.

but if I have one browser and slack open, it would be nice if it showed:

Chrome, Slack, then browsers, email, chat apps, terminal, editors, etc.

Basically just move the open apps to the front of the list.
