### ISSUE TITLE
Add `How to contribute` section.

### ISSUE THREAD

**Issue by shivanju** [pock/pock#118]
Please add a `Contributing.md` file which has steps for building locally and guidelines for project contributors and raising a PR. To be honest, this is the first time I am going to contribute to a macOs project and apart from opening it to my xcode I've no idea what to do. Though I am trying to figure it out by myself but a guide would be helpful.
Thanks.

**Comment by pigigaldi** [comment]
I’m new to this type of code contribution, so I need some time to study which tools GitHub provides to us to create a well configured open source project.
Keep suggesting new ideas to make this project more comfortable to open new PRs!
