### ISSUE TITLE
"Spacer" widget

### ISSUE THREAD

**Issue by kylehotchkiss** [pock/pock#121]
I love the pock widgets. I'm actually happy with just the now playing, date/time, and control icons. (Use case is using everything except dock) Is it possible to add a flexible space between widgets? For example, I would like escape and music on left side and the "status bar" plus icons on the right side, without a dock in the middle

**Is your feature request related to a problem? Please describe.**
I'd like the pock widgets to not bunch up on the left side if they don't take up the entire dock width

**Describe the solution you'd like**
A flexible space widget that would take up all the space in the middle so my escape button and music would be on left with status bar and brightness/volume icons would be on the right. Additionally, if there were multiple spaces inserted into dock they'd be able to evenly space things out if the user desired. In my mind is css flexboxes spacing logic if no elements have a width style set.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by Johnzzon** [comment]
Would love to see this. This is the reason I uninstalled Pock. Currently better off with just the native Expanded Control Strip. The native one has a "Space" widget that dynamically fills the empty space.

**Comment by nicpottier** [comment]
This and correct spotify icons are the only two missing pieces for me. I want just simple widgets that are always up for volume / brightness, a clock, battery and currently playing music. That makes the touch bar useful again for me without the insanity that is better touch tool. So having a spacer would be the only real thing missing.

**Comment by tomasv** [comment]
In my case I wanted to just have the "Now playing" and control icon widgets aligned to the right and the left side completely empty.

The workaround I found is adding "dock" as the leftmost element, checking "hide finder", "show only running apps", "hide persistent items" and specifying `-1000` item spacing.
Very dirty but it got the result I wanted. 😄

**Comment by silbernagel** [comment]
100 times this. Muscle memory know where the buttons should be. I loathe the touchbar with all my heart, but at least with spacers I could place them where they normally are.
