### ISSUE TITLE
[Request] disable Pock in certain apps

### ISSUE THREAD

**Issue by iDjay** [pock/pock#122]
Would be great if we can disable Pock in apps like safari so we can use the standard Touch Bar instead. I know I can switch between both Touch Bar’s manually, but it is easier if it switches automatically.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by patie** [comment]
I agree, option for disable pock touch bar for selected apps would be great, for example PhpStorm (web IDE), where i use own settings for touch bar, or Browser etc.
