### ISSUE TITLE
iStat Menus style widgets

### ISSUE THREAD

**Issue by JaredPoetter** [pock/pock#133]
A nice feature would be able to have some of the widgets like iStat Menus.

Things like:
- Temps
- Usage
- Fan Speed

**Comment by darrencornwell** [comment]
Now this is something that sounds super handy. Temps / fan speeds would be great. Maybe even a CPU load indicator.

**Comment by Eldrior** [comment]
That feature would be great! 
You can change the Activity Monitor Icon to the current CPU usage, is it possible to display that changed icon on the Touch Bar?
