### ISSUE TITLE
Pock Update Installs new pock instead of updating existing one 

### ISSUE THREAD

**Issue by tejasgarde** [pock/pock#135]
**Describe the bug**
Pock Update Installs new pock instead of updating existing one .
for example Pock 3 is available for update .New installation should update  the existing installation (or at-least delete older one ).

**To Reproduce**
install Pock 2 
Automatic Update should be ON.
This will prompt for Pock update (Pock 3)
Pock 3 will be installed but Pock 2 still in Applications

**Expected behavior**
Pock Update Installs new pock instead of updating existing one .
Older one should not be available to run.

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
- Pock 2 upgrade to Pock 3 (same with Pock to Pock 2)
<img width="1354" alt="Screenshot 2019-07-05 at 11 51 27 AM" src="https://user-images.githubusercontent.com/553219/60702042-56c20500-9f1b-11e9-8a28-007fd1581e33.png">

**Comment by MateuszDabrowski** [comment]
I just downloaded an update via Pock menu and the file was called "Pock" without any numbers. After moving it to Applications it asked if I want to replace or keep both. Clicking replace updated the app while keeping the preferences intact. All seems to be working perfectly fine.
Also MacOS Mojave 10.14.5
