### ISSUE TITLE
Allow mouse to move into Pock during use

### ISSUE THREAD

**Issue by elamje** [pock/pock#139]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am using my mouse and I naturally try to move the cursor into the Touch Bar to control some Pock function. 

**Describe the solution you'd like**
I'd like to be able to take my cursor into the Touch Bar, similar to how it is done when you are customizing the Pock dock.

**Describe alternatives you've considered**
Keyboard bindings to the controls in pock

**Comment by Samanm** [comment]
Perhaps similar to BetterTouchTool:  https://www.youtube.com/watch?v=1LUYxIRVKTw
