### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by pengoch** [pock/pock#140]
I downloaded Pock, allowed access.
And then when I click to open, nothing happens.
Touch Bar doesn't change, nothing in Preferences.
Just nothing...

**Comment by pigigaldi** [comment]
Do you have Pock icon on the MacBook's menu (status) bar?

**Comment by pengoch** [comment]
Hi

No icon.
I click on the icon on the screen, it grows and then returns to normal - as if it’s opening - then nothing


On 6 Jul 2019, at 13:56, Pierluigi Galdi <notifications@github.com> wrote:

Do you have Pock icon on the MacBook's menu (status) bar?

**Comment by isabelacmor** [comment]
I'm also seeing this. I do see the TouchBar changing to show the dock, but the Pock icon doesn't show up on the dock, so I can't access the settings to customize it.

**Comment by fcastroa** [comment]
same here, steps: I move it to app to the apps folder, double click, gives me the secuirty warning of something downloaded off the internet, I accept it, make sure that it is on accessibility panel and nothing happens. I keep double clicking on the icon but not a single thing changes on the menu, touch bar or even settings.

**Comment by A-Mil** [comment]
Same here!!  Nothing happens

**Comment by isabelacmor** [comment]
> I'm also seeing this. I do see the TouchBar changing to show the dock, but the Pock icon doesn't show up on the dock, so I can't access the settings to customize it.

I figured out my issue, which might be different from others on this thread since my TouchBar actually changes. The Pock icon **does** show up on the menu bar (top right). Maybe this should be in the docs, instead of just saying “ You can access these panes from the Preferences menu item.”

**Comment by davidherrera83** [comment]
Pock icon shows in the menu with the wifi and time, I see pock menu in touchbar but it only brings to focus already opened applications, does not open closed apps. 

macOS Mojave
version 10.14.5
MacBook Pro (15-inch, 2018)

**Comment by Neooolee** [comment]
> Pock icon shows in the menu bar (top right), I see pock menu in touchbar but it only brings to focus already opened applications, does not open closed apps.
> 
> macOS Mojave
> version 10.14.5
> MacBook Pro (15-inch, 2018)

Same here!!

**Comment by A-Mil** [comment]
Does anybody ever respond to these messages and try to help?

**Comment by vorant94** [comment]
having the same issue... the software is literally unusable for me...(
