### ISSUE TITLE
Missing Widgets

### ISSUE THREAD

**Issue by SquashFan** [pock/pock#142]
**Describe the bug**
I have installed the latest version of Pock 0.5.2 onto my MacBook Pro running 10.13.6.
The program runs fine, but only appears to give me access to the Dock Widget. The Preferences Pane shows the Dock Widget and the Status Widget, but when I go to the Customization screen, most of it is blank and doesn't let me do any customization as the attached screenshot shows.

**Versions:**
 - macOS version: 10.13.6
 - Pock version:  0.5.2

**Additional context**

**Comment by InnovativeInventor** [comment]
Could you post a screenshot/picture @SquashFan?

**Comment by SquashFan** [comment]
When I went to get the screenshots I saw that there is a new version.  I've installed it and now have access to all the widgets.  I've attached a screenshot of the new customization screen.  I did make it work, but it isn't obvious what to drag for the Now Playing, Status and Dock widgets.  The Control Center is clear but the others are blank or dimmed.  Could they be modified to show something solid to drag?  Thanks for the help.
<img width="1318" alt="Screen Shot 2019-07-06 at 21 24 29" src="https://user-images.githubusercontent.com/3231498/60763244-ee1b7b00-a035-11e9-87a3-8edc885e2f65.png">

**Comment by wayferer** [comment]
I had this issue too on first install but by chance I toggled the Show Typing option and then they appeared.

**Comment by jamesdh** [comment]
I'm on 10.14.6 w/ Pock @ 0.5.3 and I'm unable to see/select the "Control Center" widget :(

**Comment by jamesdh** [comment]
The same w/ the Escape key...

![Screen Shot 2019-08-05 at 12 31 13 PM](https://user-images.githubusercontent.com/1085322/62483516-6f714500-b77d-11e9-8b91-ae6e10481f08.png)

**Comment by avmohan** [comment]
Same. Only with the control center widget
