### ISSUE TITLE
Media widget gestures limitied space

### ISSUE THREAD

**Issue by MateuszDabrowski** [pock/pock#150]
**Describe the feature you'd like to have in Pock**
The Next/Previous song gestures on the media widget of Pock are great, but they are limited only to the size of the media widget. As this media widget is dynamically scaled to the size of song name and artists name (whatever is longer to a set cap), for a short cases (Like song "Sol" by band "Leaf") it is nearly impossible to trigger the gesture, as it almost always will go over the next widget.
It would be great if the gestures would work even if the gestures end over another widget of Pock (the starting point should count, not the ending one).

**Describe alternatives you've considered**
Another approach would be to have a fixed length of media widget (so that it always has enough space for gestures, even if it means some black space).
On one hand, it means losing some space due to a fixed length, on the other, it won't keep changing the position of icon widget every song.

**Additional context**
It seems counterintuitive and leads to people thinking it is not working at all: https://github.com/pigigaldi/Pock/issues/107#issuecomment-508909423

**Comment by MateuszDabrowski** [comment]
Should also be Enhancement ticket, but when creating a new one I can only choose between feature and bug.

**Comment by NilsJPWerner** [comment]
A minimum width would be an easy way to solve this. Though even with a wider button from a longer name, it sometimes hard to trigger the change song action.
