### ISSUE TITLE
Mute Button

### ISSUE THREAD

**Issue by FlashJunior** [pock/pock#155]
In addition to the existing volume up and down button, I would like to have a mute button ;-)

I know, you can long-touch on one of the existing Volume buttons and slide it down - but a mute button to toggle it on/off would be faster.

**Comment by luanmuniz** [comment]
I would love that too! :D

**Comment by ScoAnderson** [comment]
Instead of two buttons up/down...have a single button: short-touch to toggle mute, long-touch for slider. Have the slider manifest directly under the location of the long-touch so you can drag immediately to preferred level in a single interaction.

**Comment by luanmuniz** [comment]
> Instead of two buttons up/down...have a single button: short-touch to toggle mute, long-touch for slider. Have the slider manifest directly under the location of the long-touch so you can drag immediately to preferred level in a single interaction.

Single buttons work best for me. But it's a good idea

**Comment by uetchy** [comment]
Forked repo and added mute button. it just works.
<img width="1085" alt="Touch Bar Shot 2019-07-15 at 20 49 08" src="https://user-images.githubusercontent.com/431808/61214115-ff553d80-a741-11e9-91ce-0ded9b8a575b.png">

OK to send a pull-request?
cc @pigigaldi

**Comment by pigigaldi** [comment]
Hi @uetchy, of course! Open a new PR so I can review and merge it, alongside the others.

**Comment by uetchy** [comment]
@pigigaldi Great! I've filed [PR](https://github.com/pigigaldi/Pock/pull/172) for the mute button.

**Comment by FlashJunior** [comment]
@uetchy cool. hope it get merged soon ;-)

**Comment by FlashJunior** [comment]
thx for adding it in v0.6. the only thing i don't like is the order.

normaly you have "mute, down, up" on the keyboard:
![Order](https://cms-assets.tutsplus.com/uploads/users/31/posts/21212/image/media-keys.png)

**Comment by L1cardo** [comment]
> thx for adding it in v0.6. the only thing i don't like is the order.
> 
> normaly you have "mute, down, up" on the keyboard:
> ![Order](https://camo.githubusercontent.com/25cd809fbbc3929ab2df9f969aa30346b2a5abe7/68747470733a2f2f636d732d6173736574732e74757473706c75732e636f6d2f75706c6f6164732f75736572732f33312f706f7374732f32313231322f696d6167652f6d656469612d6b6579732e706e67)

The default Touch Bar is brightness/volume/mute/Siri, so it is better to add mute button to the right
