### ISSUE TITLE
Adjust brightness/volume in a single motion

### ISSUE THREAD

**Issue by jberglinds** [pock/pock#157]
Hi, thank you for Pock!
I have an enhancement suggestion. I'm a new user so maybe/hopefully I just missed something that's already there.

**Describe the feature you'd like to improve in Pock**
The brightness and volume buttons of the control center widget are not as easy to use as their native counterparts in the control strip. The slider is great, but to adjust it I need to first slide or hold on the button, then remove my finger before grabbing it again to adjust. If you slide the native buttons for brightness or volume the slider handle is already grabbed so you can do it in one motion. 
If this would work, a single button would be enough to make adjustments quickly, taking up less space. The volume button could mute/unmute on tap while sliding it could adjust the volume.

**Additional context**
See this article for some gifs on how the buttons in the native control strip works: https://www.howtogeek.com/305066/how-to-adjust-volume-and-brightness-in-one-gesture-on-the-macbook-pro-touch-bar/

**Comment by ScoAnderson** [comment]
RE: Volume Control:  Instead of two buttons up/down...have a single button: short-touch to toggle mute, long-touch for slider. Have the slider manifest directly under the location of the long-touch so you can drag immediately to preferred level in a single interaction.

**Comment by MacDragon** [comment]
Also a comment, the real buttons on control center support a short swipe left or right on button to do a single button push level adjustment without bringing up slider.

**Comment by uetchy** [comment]
Forked repo and added mute button. it just works.
<img width="1085" alt="Touch Bar Shot 2019-07-15 at 20 49 08" src="https://user-images.githubusercontent.com/431808/61214115-ff553d80-a741-11e9-91ce-0ded9b8a575b.png">

OK to send a pull-request?
cc @pigigaldi

**Comment by nova0052** [comment]
Please retain a two-button, non-slider control option. There are many of us who like the Pock control center widget specifically because it has up/down buttons instead of a slider.

Personally, I'd like an option to disable the slider entirely, and just use my up/down buttons.

**Comment by jberglinds** [comment]
I started using BetterTouchTool which does almost the same thing as Pock. 
It allows adjustment of volume and brightness by two- or three-finger swipes on the touch bar and I've come to realize that it's way easier to use than buttons and sliders. 
Might be the way to go for Pock as well?

**Comment by Jobey-G** [comment]
Would love the ability to change the duration of how long it takes to get to the slider function. I change brightness and volume a lot and I always find that it [too] quickly shifts to slider. To me, holding onto the volume button for 1 sec would bring up the slider, anything below that wouldn't. Currently, it feels like a quarter of a second. I prefer pressing multiple times to change as opposed to sliding. It prematurely brings up the slider too quickly.

**Comment by abhi21git** [comment]
+1
