### ISSUE TITLE
Can't have configuration as shown @ https://pock.dev

### ISSUE THREAD

**Issue by teejay-87** [pock/pock#160]
When trying to add all widgets shown in the image at https://pock.dev, on the last one I add, it replaces one already present.

Widgets are:
-esc
-now playing
-icons
-status widget
-control center widget

When adding the last one, this appears and one item gets replaced by the new one:

![image](https://user-images.githubusercontent.com/17051981/60932256-719acd80-a2bd-11e9-8379-4388a786cc79.png)

**Comment by ladamalina** [comment]
I have this issue too. Can place only four widgets, no more.
MacBook Pro 13-inch, 2017
macOS Mojave 10.14.5

**Comment by citylife4** [comment]
I've found and an workaround for this issue:

1. Add all the available widgets minus the status
2. Go to preferences and remove some bottoms from the control widget, F.E the "Show volume Up" and "Show Brightness Up"
3. Add the status widget
4. Revert the control widget modifications.

Screenshot of my Touch Bar:
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/5374170/76567442-a98a8e00-64a6-11ea-96f8-2e23170fd74e.png">

MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
macOS Catalina 10.15.3
