### ISSUE TITLE
No Esc button while browsing finder from pock

### ISSUE THREAD

**Issue by TechieGenie** [pock/pock#161]
I am trying to edit a file in Vim and started browsing in finder from Pock menu. I don't see <kbd>Esc</kbd> button to save the file while in Vim. I have to close the finder browser to get the <kbd>Esc</kbd> back.

**Comment by TechieGenie** [comment]
If anyone else is facing this problem and want the <kbd>Esc</kbd> button back, you can double press <kbd>Ctrl</kbd> and it will close the `Pock` Strip. Double pressing <kbd>Ctrl</kbd> again will restore the finder browser at the exact place where you're browsing.

**Comment by pigigaldi** [comment]
The `esc` button was not added on folder presentation intentionally since you can use `fn` key or the double `ctrl` shortcut to reach the desired key.
I'll move this to `enhancement` and I'll add an option to enable `esc` key in folder presentation too 👍
