### ISSUE TITLE
Flotato Apps not displaying correctly

### ISSUE THREAD

**Issue by MayerMediaCo** [pock/pock#180]
**Describe the bug**
A clear description of what the bug is.

Apps created using “Flotato” do not display seperate icons in the touchbar, but do so in the actual dock.

**How to reproduce**

Create and open multiple apps with Flotato

**Expected behavior**
A clear description of what you expected to happen.

Seperate icons should display for seperately docked items

**Screenshots**
`To take a Touch Bar screenshot use the shortcut "shift + cmd + 6”`

Twitter and Github are apps created using Flotato

<img width="842" alt="Screen Shot 2019-07-25 at 11 45 17 AM" src="https://user-images.githubusercontent.com/36319210/61892660-e717b800-aed1-11e9-917f-1e0fc62f386c.png">
<img width="1085" alt="Touch Bar Shot 2019-07-25 at 11 44 54 AM" src="https://user-images.githubusercontent.com/36319210/61892674-eaab3f00-aed1-11e9-9c0e-62a36ddf823a.png">

**Crashlog**
If applicable, add crashlog to help me investigate your problem.

Not Applicable

**Versions:**
 - macOS version: 10.14.5
 - Pock version:  0.5.3

**Additional context**

**Comment by elimuhub** [comment]
flatato apps
