### ISSUE TITLE
[Request] Don't open iTunes when clicking on "Now Playing" widget 

### ISSUE THREAD

**Issue by bolinocroustibat** [pock/pock#183]
It would be great if Pock wasn't opening iTunes when clicking on "Now Playing" widget while no song was playing.
Alternatively, user could be able to set the music app associated with the widget.

**Comment by ahmedu007** [comment]
I like that fact it opens the iTunes, but it's because I use Apple music. I can see why that would be nice to let the user configure it in settings somewhere.
