### ISSUE TITLE
I don't get this - Pock goes out of the touch bar when I switch apps 

### ISSUE THREAD

**Issue by souljacker** [pock/pock#187]
Pock appears on my touch bar whenever Pock is selected, otherwise it goes away and the same old boring touch bar gets in its place. Am I doing something wrong? Is that a way of keeping it there?

**Comment by josephsiu** [comment]
You have to enable the option "Hide controls strip" to persist Pock

**Comment by shirshak55** [comment]
@josephsiu I need to use those control strips etc for screenshots etc.? Is there no way to use it without hiding control strips?

**Comment by josephsiu** [comment]
If ran normally, Pock acts like another other app so when another app have default touchbar actions, Pock will be replaced; hiding the control strip will make it stay. There should be a hotkey listed that will allow pock to hide/show even with that option.

**Comment by shirshak55** [comment]
no it dont work even if i do thay. some app like chrome changes it and it
never shows again.

**Comment by krystah** [comment]
What is even up with the complete lack of support / troubleshooting for this project? It looks nice and flashy, but what are we supposed to do when it doesn't work as advertised and you provide no guidelines?

**Comment by shirshak55** [comment]
You cannot say that to open source project man.The software is provided
without any warranty.

**Comment by krystah** [comment]
It's not about expecting a service; any serious project (especially one subtly encouraging donations) should have documented code. This is not only for maintenance purposes, it would also make users (like myself) more self-reliant in debugging. Don't mind me though, I found a different project

**Comment by shirshak55** [comment]
if you have found other project let us know too :) By the way the
documentation is not for code but for use of software right? And I think
they have covered it just install it and use it :)

**Comment by ahmedu007** [comment]
![image](https://user-images.githubusercontent.com/30743917/62634549-00871e00-b92e-11e9-805c-0ad8348a011c.png)

Mine works perfectly. Just install it and put it in applications and boom

**Comment by shirshak55** [comment]
@ahmedu007 u will notice after few hour how it disappears and never comes back :(

**Comment by ahmedu007** [comment]
@shirshak55  I've been using it for a few months now, and it works fine. I shutdown my Mac most of the nights, because I dont want the VM's and containers to keep running, so even after the reboot it comes back on as it should. Although I did have to add it to the startup option, but that's it

**Comment by AsydRayn** [comment]
I'm still trying to figure out how to switch between widgets or if it's possible, haven't found full documentation yet. Double tapping the control buttons opens and closes the same widget.
