### ISSUE TITLE
Brightness resets after a few seconds

### ISSUE THREAD

**Issue by lcukerd** [pock/pock#190]
**Describe the bug**
Screen brightness to normal after the brightness slider is closed. Works fine when tapping to adjust the brightness.

**How to reproduce**
1. Open brightness slider
2. Change brightness and close slider
3. Brightness changes back to normal.

**Expected behavior**
Brightness should persist

**Versions:**
 - macOS version: 10.14.6
 - Pock version:  0.5.3

I am not sure how to fix this or where to find help (Where do you ask?). Was planning to do [#157](https://github.com/pigigaldi/Pock/issues/157) and multi-finger swipe gesture this weekend but they will be useless if brightness slider doesn't actually work.

**Comment by willvousden** [comment]
For the record, I'm having this problem with Pock 0.7.1 and 10.15.1.

**Comment by Jobey-G** [comment]
I do not have this problem. I am on 0.7.2 and 10.15.2

**Comment by AndreCNF** [comment]
I also have this problem, with the brightness resetting even if only after a couple of minutes (although I have the automatic brightness adjustment turned off). I have pock 0.7.2 and macOS Catalina 10.15.1.

**Comment by MarceloZapatta** [comment]
I have this issue, but not a mac user, I'm on Debian 10 with KDE Plasma 5.14. Turn out look's like is because I have an app "Red Shift" installed, which after a few seconds are resetting my brightness configuration.

Disable RedShift works for me. Maybe some app are doing the same thing in your OS.
