### ISSUE TITLE
MS Teams / Skype - Microphone Mute / Unmute Buttons

### ISSUE THREAD

**Issue by liambresnahan** [pock/pock#198]
**Describe the feature you'd like to have in Pock**
When using MS Teams or MS Skype for Business there is often a time where a user will want to mute and unmute the microphone to enable talking. It would be great to have a single icon in the Touch Bar that can be added like the Spotify widget that will allow for this. 

**Describe alternatives you've considered**
SfB offers Touch Bar support today (when the app is selected). MS Teams does not

**Comment by bampotent** [comment]
I second this! I use MS Teams daily and have to move the mouse about to find the mute button in the app to mute/unmute. This would be valuable if MS Teams/Skype for Business is not the app in focus - there have been times when I have been multi-tasking and lost the MS Teams window when needing to unmute and make a comment
