### ISSUE TITLE
Microsoft Teams does not work

### ISSUE THREAD

**Issue by stuartaylward** [pock/pock#20]
The MS Teams icon does not show on the touchbar dock, instead you get a default ios icon, which highlights when you're in Teams app, but pressing on it does nothing also.

**Comment by JCHHeilmann** [comment]
Same issue for me.

**Comment by teroelonen** [comment]
I have the same issue.

**Comment by thtliife** [comment]
I get the same thing here.
I am on pock v0.4.6 and MacOS Mojave 10.14.5 Beta
I do know that teams is an Electron App, as is the code editor, Atom.
One thing i note, is that the icon displayed in teams is the same generic application icon as the one for the Microsoft Teams Helper process in Activity Monitor.
![Teams processes vs Atom processes](https://user-images.githubusercontent.com/9210782/57409092-ba38fa80-722a-11e9-8fb7-dca546d928e0.png)

I also notice that Atom Editor works just fine in pock, i wonder if there are any significant differences between them?

**Comment by jannikeskinis** [comment]
Some news or updates for this issue ? Would be nice to get it fixed! Thank you in advance!

**Comment by thtliife** [comment]
Weird thing.... today i notice ms teams is working, and yet i am still on pock v0.4.6?

**Comment by krsilas** [comment]
I solved the issue by changing the icon of "Microsoft Teams Helper". Rightclick Teams in Finder > "Show package contents" > Contents > Frameworks and then follow [these instructions](https://support.apple.com/guide/mac-help/create-custom-icons-files-folders-mac-mchlp2313/mac#mchlp3d912e2). Don't worry if the icon doesn't show up in the info preview. It has to be an icns-file though. [Here's one](https://file.io/jZCI5i). 
Restart Teams and voilà! 😊
You can also open the app by touching it on 0.5.1

**Comment by shanep2300** [comment]
Thanks @krsilas that helped with the icon. Touching the icon in 0.5.3 doesn't open it but I do see that status bar change showing that it's focused.

**Comment by mwarrenus** [comment]
The MS Teams icon shows up properly for me in Pock v0.7.2. Teams v1.3.00.9271.

**Comment by fluktuid** [comment]
The Teams icon shows up correctly when I start teams.
When the teams notification process is started, the icon changes to the wrong icon.

> I solved the issue by changing the icon of "Microsoft Teams Helper". Rightclick Teams in Finder > "Show package contents" > Contents > Frameworks and then follow these instructions. Don't worry if the icon doesn't show up in the info preview. It has to be an icns-file though. Here's one.
Restart Teams and voilà! 😊
You can also open the app by touching it on 0.5.1

@krsilas this results in an "empty" logo on my machine.

**Comment by fluktuid** [comment]
Teams use an extra app that handles the notifications.
It is called anders has a different app icon.

**Comment by fluktuid** [comment]
issue still present
