### ISSUE TITLE
Add instructions for enabling to your website

### ISSUE THREAD

**Issue by arnavb** [pock/pock#202]
**Describe the feature you'd like to have in Pock**
Currently, in order to find out how to enable this app, one has to head to the [README file](https://github.com/pigigaldi/Pock#how-to-enable) from the Github link on your website. This seems like a lot of hassle, when everything should be on the website itself (unless I missed it, in which case the instructions should be more clearly visible).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by smcfaddin47** [comment]
Did you get Pock to run? I have done all the settings from the README file but I still cannot get Pock to run. I click on the application and nothing happens

**Comment by arnavb** [comment]
@smcfaddin47 i can’t really say anything about your problem since that seems to be a separate issue. I would recommend you open a new issue so that the maintainers of this app can help you.
