### ISSUE TITLE
Disappears from touchbar when changing user profiles

### ISSUE THREAD

**Issue by tommoor** [pock/pock#212]
**Describe the bug**
The touchbar reverts to standard functionality when changing between user profiles, even when Pock is installed in both profiles. The Pock menubar icon remains. I have two users on my machine for home / work and it means that it disappears every day as I switch between them.

**How to reproduce**

1. Have multiple user accounts on your Mac
1. Install Pock on both
1. Switch between users

**Expected behavior**
Pock should continue to run in the touchbar.

**Versions:**
 - macOS version: 10.14
 - Pock version:  0.6

**Comment by Alinaki** [comment]
Also affects me on Catalina 10.15.1
