### ISSUE TITLE
Tidal Icon Support

### ISSUE THREAD

**Issue by joshmedeski** [pock/pock#213]
**Describe the feature you'd like to improve in Pock**
I would love if the [Tidal](https://tidal.com/) music icon is visible when playing music from that app in Pock!

**Additional context**
If it's a simple feature change I may be able to dig into the code and do it for you! I would just need some basic instructions for where to look.

**Comment by kaptankorkut** [comment]
+1

**Comment by itzsaga** [comment]
Opened up a PR to accomplish this 😄
