### ISSUE TITLE
Pock will be crashed when pressing QQ icon

### ISSUE THREAD

**Issue by wxxhq** [pock/pock#216]
**Describe the bug**
I have tried to press other app icon on the pock and only QQ will let Pock crashed.I thought it was accidental. After repeated several times, it would still crashed.

**Crashlog**
Process:               Pock [98098]
Path:                  /Applications/Pock.app/Contents/MacOS/Pock
Identifier:            com.pigigaldi.pock
Version:               0.6 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Pock [98098]
User ID:               501

Date/Time:             2019-08-24 09:16:32.818 +0800
OS Version:            Mac OS X 10.14.6 (18G87)
Report Version:        12
Bridge OS Version:     3.0 (14Y904)
Anonymous UUID:        0267039F-A4BC-735E-4DF9-C16EA18915F6

Sleep/Wake UUID:       19EA328A-A599-4155-8AFB-6A9665ED0413

Time Awake Since Boot: 560000 seconds
Time Since Wake:       2500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [98098]

Application Specific Information:
Performing @selector(_didTriggerPressGestureRecognizer:) from sender NSPressGestureRecognizer 0x600003a7be90
*** CFRelease() called with NULL ***

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff2ef2eced CFRelease + 109
1   com.pigigaldi.pock            	0x0000000108081116 0x10807e000 + 12566
2   com.pigigaldi.pock            	0x0000000108080f2a 0x10807e000 + 12074
3   com.pigigaldi.pock            	0x000000010809892a 0x10807e000 + 108842
4   com.pigigaldi.pock            	0x0000000108092121 0x10807e000 + 82209
5   com.pigigaldi.pock            	0x00000001080a3ed7 0x10807e000 + 155351
6   com.pigigaldi.pock            	0x00000001080a41ff 0x10807e000 + 156159
7   com.apple.AppKit              	0x00007fff2c9ecdaf -[NSScrubber _didTriggerPressGestureRecognizer:] + 973
8   com.apple.AppKit              	0x00007fff2c848644 -[NSApplication(NSResponder) sendAction:to:from:] + 312
9   com.apple.AppKit              	0x00007fff2c84835c _NSGestureRecognizerSendActions + 204
10  com.apple.AppKit              	0x00007fff2c847af8 -[NSGestureRecognizer _updateGestureWithEvent:] + 867
11  com.apple.AppKit              	0x00007fff2c84777a -[NSGestureRecognizer _delayedUpdateGesture] + 60
12  com.apple.AppKit              	0x00007fff2c847726 ___NSGestureRecognizerUpdate_block_invoke + 51
13  com.apple.AppKit              	0x00007fff2c6c5596 _NSGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 282
14  com.apple.AppKit              	0x00007fff2c6c4d8c _NSGestureRecognizerUpdate + 1450
15  com.apple.AppKit              	0x00007fff2cb7ceba ___NSSendDirectTouchesEvent_block_invoke + 3235
16  com.apple.AppKit              	0x00007fff2cbf5923 -[NSTouchDevice _preventFlushingContextID:during:] + 169
17  com.apple.AppKit              	0x00007fff2cb7c187 _NSSendDirectTouchesEvent + 544
18  com.apple.AppKit              	0x00007fff2cb7111c _NSSendEventToDequeuingObservers + 337
19  com.apple.AppKit              	0x00007fff2c5558fa -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2496
20  com.apple.AppKit              	0x00007fff2c54f5a8 -[NSApplication run] + 699
21  com.apple.AppKit              	0x00007fff2c53eae8 NSApplicationMain + 777
22  com.pigigaldi.pock            	0x0000000108082399 0x10807e000 + 17305
23  libdyld.dylib                 	0x00007fff5aeb53d5 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff5b0a83f0 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff5b0a83f0 start_wqthread + 0

Thread 3:: com.twitter.crashlytics.mac.MachExceptionServer
0   libsystem_kernel.dylib        	0x00007fff5afedf4a write + 10
1   com.pigigaldi.pock            	0x00000001080dd2b3 0x10807e000 + 389811
2   com.pigigaldi.pock            	0x00000001080d4e05 0x10807e000 + 355845
3   libsystem_pthread.dylib       	0x00007fff5b0a92eb _pthread_body + 126
4   libsystem_pthread.dylib       	0x00007fff5b0ac249 _pthread_start + 66
5   libsystem_pthread.dylib       	0x00007fff5b0a840d thread_start + 13

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff5b0a83f0 start_wqthread + 0

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff5afea22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5afea76c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2ef601ee __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff2ef5f75c __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff2ef5eebe CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff2c55e4c2 _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff5b0a92eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5b0ac249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5b0a840d thread_start + 13

Thread 6:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	0x00007fff5afea22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5afea76c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2ef601ee __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff2ef5f75c __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff2ef5eebe CFRunLoopRunSpecific + 455
5   com.apple.CFNetwork           	0x00007fff2de45380 -[__CoreSchedulingSetRunnable runForever] + 210
6   com.apple.Foundation          	0x00007fff311b95c2 __NSThread__start__ + 1194
7   libsystem_pthread.dylib       	0x00007fff5b0a92eb _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff5b0ac249 _pthread_start + 66
9   libsystem_pthread.dylib       	0x00007fff5b0a840d thread_start + 13

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff5b0a83f0 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fff2f2a752f  rbx: 0x0000000000000000  rcx: 0xc30e3d24a44d0013  rdx: 0x0000000000000001
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x00007ffee7b801d0  rsp: 0x00007ffee7b801d0
   r8: 0x0000000000000607   r9: 0x0000000000000000  r10: 0x00000000ffffffff  r11: 0x0000000000000206
  r12: 0x0000000000000000  r13: 0x00007fff596d9680  r14: 0x0000000000000000  r15: 0x743ea1b00bd9acc1
  rip: 0x00007fff2ef2eced  rfl: 0x0000000000010246  cr2: 0x00000001081f9000
  
Logical CPU:     2
Error Code:      0x00000000
Trap Number:     6

**Versions:**
 - macOS version: 10.14.6 (18G87)
 - Pock version: 0.6

**Comment by ceej7** [comment]
This bug also happens to me and is really nettlesome, please fix it as soon as possible

**Comment by GefeiSHEN** [comment]
Same bug here, please fix this when you have time, thank you!

**Comment by StevenKSaint** [comment]
When i touch QQ ico, all of Pock crash, please fix this , thank you .i like this program very much.

**Comment by L1cardo** [comment]
This didn’t happen to me .
