### ISSUE TITLE
Use other button to switch bar instead of double pressing control

### ISSUE THREAD

**Issue by zhouxingchijared** [pock/pock#224]
Please add the option to switch bar with other key combination or double pressing some other key

For some users, for example multilingual users who frequently switch keyboards or who use many shortcuts that has ```control``` key as combination, it is very easy to mistakenly double press ```control```. please add the option to customize key combination to switch bar or the option to disable double pressing ```control``` key under ```Hide Control Strip``` option

I really appreciate.

**Comment by Altair-Bueno** [comment]
This is kinda annoying if you are using a JetBrains IDE, like IntelliJ or WebStorm. Double pressing control conflicts with `run command`

I do not have any kind of knowledge on Swift to add this functionality myself, but i know that [sindresorhus has a small library](https://github.com/sindresorhus/KeyboardShortcuts) for this specific purpose
