### ISSUE TITLE
Microsoft Teams crashes Pock

### ISSUE THREAD

**Issue by pr0gstar** [pock/pock#228]
**Describe the bug**
If you try to go to MS Teams via Pock over the Touchbar then Pock crashes.

**How to reproduce**
Run Microsoft Teams and Click on Teams Icon in Touchbar.

**Expected behavior**
MS Teams should open and not Crash Pock

**Versions:**
 - macOS version: 10.14.6
 - Pock version:  0.6
 - MS Teams: 1.2.00.21868

**Comment by bampotent** [comment]
Yep - me too - this is quite annoying. I find when Teams is closed nothing happens when tapping on the icon. When Teams is running and I try to switch to activate it then it crashes Pock

**Comment by adhuston** [comment]
Happens to me as well.  When Pock doesn't crash, I normally see a generic app icon in place of the Teams icon, and upon occasion the icon continually bounces in Pock.

**Comment by fluktuid** [comment]
Teams use an extra app that handles the notifications.
It is called anders has a different app icon.

A workaround can be found [here](https://github.com/pigigaldi/Pock/issues/20#issuecomment-630837635).
