### ISSUE TITLE
Pock not displaying / running (Followed all instructions)

### ISSUE THREAD

**Issue by garethza** [pock/pock#231]
**Describe the bug**
Pock does not display on my touch bar, even though i have followed all the installation instructions and 'opened' the app

**How to reproduce**
Just try to open the app

**Expected behavior**
Pock displays on my touch bar

**Screenshots**

![image](https://user-images.githubusercontent.com/24209093/64851092-9b9aa400-d60e-11e9-977b-16c3af2768df.png)
![image](https://user-images.githubusercontent.com/24209093/64851115-a9502980-d60e-11e9-9f37-52f20752c503.png)

**Crashlog**
No crash report is generated

**Versions:**
 - macOS version: 10.14.6
 - Pock version:  Latest (0.6)

**Additional context**
I have had 'BetterTouchTool' installed in the past but I have removed it fully incase it was conflicting with Pock

**Comment by nathanaskinner** [comment]
I am having this issue as well.

**Comment by pigigaldi** [comment]
Does Pock icon appear in the Menu Bar?

**Comment by garethza** [comment]
Nope, nothing appears at all

**Comment by smcfaddin47** [comment]
Agreed. I am running 14.2 and have installed, fully removed, reinstalled Pock so many times. All settings are done as instructed but the app never runs
