### ISSUE TITLE
Dock should switch Spaces

### ISSUE THREAD

**Issue by brio1337** [pock/pock#237]
I would like the Dock in Pock to completely replace the Dock built into macOS.

With the native Dock, if I click on an app that has no windows on the current space, but does on another, it will automatically switch to the Space so I can see the window. It usually does this on the second click. I like this behaviour.
If I use Pock's Dock to activate an app that has no windows on the current space, but does on another, the space is not switched to. Now I have to switch spaces until I find it.

**Comment by AjitZero** [comment]
> If I use Pock's Dock to activate an app that has no windows on the current space, but does on another, the space is not switched to. Now I have to switch spaces until I find it.

This behaviour already works for me, for regular windows and full-screen apps as well. Which version of Pock are you on?

I'm on Pock 0.6.3 on Mac OS 10.15.1 (19B88), MacBook Pro (15-inch, 2018).

**Comment by Jobey-G** [comment]
I have the same problem albeit a few differences.

With the native Dock, I click once and it will take me to the app, whether it be a fullscreen app (like Safari/Mail/Calendar that I have in fullscreen mode) or Messages/Notes/Slack that are within a space.

In Pock, however, when I click a fullscreen app, it will not take me to the app, instead it takes me to the first (very far left space). When I click an app that is NOT in a fullscreen mode, it takes me to that app in whichever space it resides in.

**Comment by c00kiemon5ter** [comment]
Using pock `0.8.1-5` this works fine for me.

An issue I see is that multiple windows are not recognized.
