### ISSUE TITLE
Pock application was running but nothing showing up in the status bar

### ISSUE THREAD

**Issue by Glory-Michael** [pock/pock#257]
**Describe the bug**
The pock application is running as expected, but the pock icon cannot be found in the status bar, meaning the user cannot change the preference of the application and have to go to Activity Monitor to close Pock. 

**Expected behavior**
Pock icon showing up on status bar.

**Versions:**
 - macOS version: 10.15
 - Pock version:  0.6.2

**Additional context**
I've tried to reinstall the application and reset it, but the setting preserves after reinstallation, meaning the icon still didn't show up. Restart the mac doesn't help.

**Comment by mmmmmtheus** [comment]
I have the same problem. It would be nice to have the button we had before in Control Strip

**Comment by omahonyb** [comment]
I only installed this today on my mac, and was wondering what was wrong.
Does anyone know what version i should revert to until this resolved.

**Comment by RonanMacF** [comment]
Similar issue with same version of Pock and macOS. Have checked the permissions and ensured they are all enabled. Tried re-installing it, restarting computer but nothing can get the touch bar to change.

**Comment by milieu** [comment]
was this fixed?
