### ISSUE TITLE
Pock is still running but not working after waked up from sleep.

### ISSUE THREAD

**Issue by vroyibg** [pock/pock#261]
**Describe the bug**
After macbook waked up from sleep. Pock is running but nothing happen with the touch bar, need to manually quit then relaunch to fix.

**How to reproduce**
```
1. Open pock everything works fine.
2. Close macbook lip let it go into deep sleep.
3. Open lip , login.
4. Pock is still running, the icon show up on status bar, configuration work fine, but the touch bar is not modified.
5. Quit pock, and launch it again fix the problem.
```

**Expected behavior**
Pock work after mac waked up from sleep.

**Versions:**
 - macOS version: 10.15
 - Pock version:  0.6.2

**Comment by pigigaldi** [comment]
Hi, could you please provide more information about your Touch Bar and Pock setup?

**Comment by vroyibg** [comment]
All my settings is at default, only Launch  at login checked, i noticed that this isn't only way happening, sometimes it works fine after wake up, sometimes it doesn't.

**Comment by zhengweidi** [comment]
I have the same problem.

**Comment by adur1990** [comment]
I would give that issue a +1, although I can not provide more information.

Pock Version: 0.7.2
macOS: 10.14.6 (18G103)
Preferences:
![control_center_widget](https://user-images.githubusercontent.com/10381899/71180040-b0bc4a00-2271-11ea-9387-0cffdb0baa4a.png)
![dock_widget](https://user-images.githubusercontent.com/10381899/71180042-b0bc4a00-2271-11ea-937b-ee6f79f18112.png)
![general](https://user-images.githubusercontent.com/10381899/71180045-b154e080-2271-11ea-973c-7cb0cfb8b81f.png)
![now_playing_widget](https://user-images.githubusercontent.com/10381899/71180046-b154e080-2271-11ea-9bac-015e2b7c5db4.png)
![status_widget](https://user-images.githubusercontent.com/10381899/71180048-b154e080-2271-11ea-8f0b-deff210cf6d7.png)

Thanks for your great work!
