### ISSUE TITLE
Can't open the pock in the system Touch Bar

### ISSUE THREAD

**Issue by Yilimmilk** [pock/pock#264]
After tap the exit round button,I can't open the pock on the right side  in the Touch Bar .

**Screenshots**

<img width="1085" alt="触控栏快照2019-10-22下午10 52 56" src="https://user-images.githubusercontent.com/17375605/67299047-ba9a2900-f51e-11e9-9497-63a204dbb622.png">

<img width="1085" alt="触控栏快照2019-10-22下午10 51 42" src="https://user-images.githubusercontent.com/17375605/67298946-9b030080-f51e-11e9-846d-753953669e58.png">

**Versions:**
 - macOS version: [10.15]
 - Pock version:  [0.6.2]

**Comment by Yilimmilk** [comment]
It's not happened every time,but sometimes

**Comment by DarthPestilane** [comment]
same here.

**Comment by pigigaldi** [comment]
Did you try using the `double ctrl key` shortcut to bring Pock back?

**Comment by KingsleyYoo** [comment]
I have a similar problem. When I open pock app in my macbook (macOS 10.15.1), the touchbar cannot showing any dock icon. I try using the double ctrl key shortcut, the issue also exists.
I wanna konw 

<img width="1085" alt="触控栏快照2019-11-05上午11 58 05" src="https://user-images.githubusercontent.com/20521959/68177547-9ed55f00-ffc3-11e9-8e92-55e7e719b1c6.png">
how to solve the issue.

**Comment by pinotao** [comment]
the same. And pock cannot unable to switch with other apps' custom touch bar

**Comment by Yilimmilk** [comment]
> Did you try using the `double ctrl key` shortcut to bring Pock back?

I have tried，It also can‘t work sometimes

**Comment by Keloran** [comment]
if you have bettertouchtool with Touch Bar support turned on, the "pock button" in control panel (standard) won't appear its being overridden
