### ISSUE TITLE
Unable to switch between pock and system dock using the control key

### ISSUE THREAD

**Issue by liuxianghua1** [pock/pock#265]
I do not know what to do

**Comment by lordofthewolves** [comment]
Press the control key twice quickly to switch.

**Comment by WillBishop** [comment]
This doesn't work for me on Catalina

**Comment by pigigaldi** [comment]
@liuxianghua1 can you provide more information about your setup?

@WillBishop, please, read the information [here](https://pock.dev/docs/catalina.html) for setting the right permission in macOS Catalina.

**Comment by HanMs** [comment]
Unable to switch between pock and system dock using the control key
@pigigaldi  I also encountered this problem ：10.14.6 (18G2022)

**Comment by HanMs** [comment]
command + Q Forced exit, reopened to normal

**Comment by brendony** [comment]
I had these symptoms on Mojave (10.14.6). As @HanMs mentioned, quitting Pock and restarting seems to have fixed my problems.

My thanks to the devs!
