### ISSUE TITLE
Keep the touchbar visible at all times when turned on

### ISSUE THREAD

**Issue by gsprenger** [pock/pock#269]
**Describe the feature you'd like to have in Pock**
Currently the touch bar goes to sleep/disappears after a moment of inactivity. This prevents from seeing the dock within the touch bar at a glance and see notification icons (red dot from Slack, Outlook etc.).
This feature would keep it always on (unless the mac goes to sleep of course), maybe togglable with a settings option in case some people would actually prefer to have it disappear when not using the computer actively.

**Describe alternatives you've considered**
It's easy to get the touch bar to wake up by just tapping it or moving the mouse but that requires actual movement, vs. being able to just look at it. I don't know how hacky one has to get to get this behaviour to work so if there isn't a clean way to do this let's just close this.

**Additional context**
There's some additional info about this here: (not my post) 
https://apple.stackexchange.com/questions/269174/disable-the-sleep-function-of-the-macbook-touch-bar

**Comment by timrspratt** [comment]
My touch bar suffers from a fault where the right side slashes white when the touch bar sleeps. It's out of warranty and costs $1,000 to fix so ideally being able to prevent the touch bar sleeping will be ideal 😊
