### ISSUE TITLE
Match order of opened apps in TouchBar and Dock

### ISSUE THREAD

**Issue by somepage** [pock/pock#283]
**Describe the feature you'd like to have in Pock**
Now in 'show only running apps' mode orders of apps in TouchBar and dock doesn't match. If they match, it will be more comfortable and UX.

**Comment by Jobey-G** [comment]
I agree as well!

**Comment by 81joe81** [comment]
Yes, please!

**Comment by LinusGeffarth** [comment]
Second this!
