### ISSUE TITLE
App expose doesn't work with Visual Studio Code

### ISSUE THREAD

**Issue by RobSjaras** [pock/pock#285]
**Describe the bug**
Visual Studio Code (VSC) is not being registered as having multiple windows open, even though I have 3-4 windows open. Instead it just switches to the desktop with the most recently used VSC window.

**How to reproduce**
```
1. Open multiple windows of VSC
2. Click on VSC on the touch bar
3. See error
```

**Expected behavior**
The multiple are expected to appear on the touch bar

**Versions:**
 - macOS version: 10.15.1
 - Pock version:  0.6.3

**Additional context**
Otherwise loving the app so far, keep up the good work!

**Comment by idoo** [comment]
@pigigaldi duplicate of https://github.com/pigigaldi/Pock/issues/284
