### ISSUE TITLE
When opening a new program Pock disappears for a flash (shows normal touchbar) and then comes back

### ISSUE THREAD

**Issue by nogills** [pock/pock#287]
This didn't happen in Mojave, just started since I updated to Catalina 10.15.1 

It works as expected until I open a new app and then Pock goes away for like half a second and you can see the stock touch bar controls, and then Pock comes back. Not a huge deal, just not very visually pleasing.

EDIT: also I just realized that if I click the applications or download folders on the dock, Pock completely goes away until I click away from the folder.

**Comment by L1cardo** [comment]
This also appears when you click control center widgets.
This issue happens to me too.
