### ISSUE TITLE
Finder doesn't work with multiple workspaces

### ISSUE THREAD

**Issue by Apidcloud** [pock/pock#290]
**Describe the bug**
Clicking on the 'Finder' icon doesn't work when the Finder window is in a workspace other than the one you are currently at. If there is a window in the workspace, however, it brings it up correctly.

**How to reproduce**
Steps to reproduce the behaviour:
```
1. Go to 'Preferences' and disable 'Opens finder and directories inside Pock'
2. Open a Finder window in Workspace 1
3. Go to Workspace 2 (with no Finder windows)
4. Click on 'Finder' in the touchbar icon (Pock)
5. Nothing happens.
```

**Expected behaviour**
It should do the same it does with the other apps that are in another Workspace: move to the correct workspace and bring it to the top. That's the behaviour when I click on the 'Finder' from the standard Mac Dock.
```

**Versions:**
 - macOS version: 10.14.6
 - Pock version: 0.6.3

**Comment by Jobey-G** [comment]
> ```
> 1. Go to 'Preferences' and disable 'Opens finder and directories inside Pock'
> 2. Open a Finder window in Workspace 1
> 3. Go to Workspace 2 (with no Finder windows)
> 4. Click on 'Finder' in the touchbar icon (Pock)
> 5. What happens to me is if you look at the Menu Bar at the top, it shows Finder, meaning you could press "CMD + N" to get a new window but like **Apidcloud** I like my windows to be in the same Space. Would be great if when clicking Finder in Pock, it took you to the Space with the Finder windows within it.
> ```

**Comment by Jobey-G** [comment]
1. Go to 'Preferences' and disable 'Opens finder and directories inside Pock'
2. Open a Finder window in Workspace 1
3. Go to Workspace 2 (with no Finder windows)
4. Click on 'Finder' in the touchbar icon (Pock)
5. What happens to me is if you look at the Menu Bar at the top, it shows Finder, meaning you could press "CMD + N" to get a new window but like Apidcloud I like my windows to be in the same Space. Would be great if when clicking Finder in Pock, it took you to the Space with the Finder windows within it.

**Comment by Apidcloud** [comment]
Ah, true. But it's not the same behaviour as clicking on Finder in the dock
