### ISSUE TITLE
Allow re-ordering of Control Center Widget

### ISSUE THREAD

**Issue by willvousden** [pock/pock#301]
**Describe the feature you'd like to improve in Pock**
It would be nice to be able to re-order the buttons in the Control Center Widget.

Specifically, it's frustrating not to have the Lock button next to the physical Touch ID button.  I use these very often (I have to lock my machine at work when I'm away from my desk), and having these two buttons next to each other is much better UX for me.

**Describe alternatives you've considered**
An easier solution to my specific problem would be to hard-code the Lock button at the right of the Control Center Widget.  This would probably make sense from a UX perspective, but it obviously doesn't solve the general problem.

**Additional context**

<img width="1085" alt="Touch Bar Shot 2019-12-11 at 12 21 24" src="https://user-images.githubusercontent.com/152388/70617476-f6916680-1c10-11ea-92d1-e19a3c31e725.png">

**Comment by Jobey-G** [comment]
I agree too. Lock button next to the Touch ID is where I would like to put it too. Would be nice to have full control where you put the Control Center. Keyboard Brightness would also be a welcome addition.

**Comment by PsiPhiTheta** [comment]
Agree, we should be able to reorder Control Center Widget
