### ISSUE TITLE
Control center buttons not working

### ISSUE THREAD

**Issue by Darktortue** [pock/pock#317]
**Describe the bug**
When i show brightness up/down item and volume up/down item it doesn't work. 

**How to reproduce**
```
1. In Pock, go to Preferences, Control Center Widget
2. Click on "Show Brightness up/down Item"
3. Click on Click on "Show Volume up/down Item"
4. When you type it on the touch bar, nothing happens
```

**Expected behavior**
When you type any of the 4 items on the touch bar, you expect that the brightness goes up or down, or that the volume goes up or down.

**Screenshots**
<img width="466" alt="Capture d’écran 2019-12-17 à 18 10 41" src="https://user-images.githubusercontent.com/11302315/71018812-7760ce80-20f9-11ea-81f8-c3b9dbec354b.png">
<img width="1085" alt="Capture d’écran Touch Bar 2019-12-17 à 18 17 04" src="https://user-images.githubusercontent.com/11302315/71018945-bb53d380-20f9-11ea-8875-c656ce4fa501.png">

**Versions:**
 - macOS version: 10.15.2
 - Pock version:  0.7.2

**Comment by talisto** [comment]
Did you allow these permissions? https://pock.dev/docs/catalina.html

**Comment by Darktortue** [comment]
Yep I already did that from day 1 on Catalina but the strange thing is that i cannot allow Pock in the Screen Recording category. It just doesn't show up. I already uninstalled 10 times Pock but it doesn't change anything.

<img width="777" alt="Capture d’écran 2020-01-14 à 18 57 45" src="https://user-images.githubusercontent.com/11302315/72369228-f00a7900-36ff-11ea-9fa7-ae5369d25384.png">

**Comment by mediter** [comment]
> **Describe the bug**
> When i show brightness up/down item and volume up/down item it doesn't work. 
> 
> **How to reproduce**
> Steps to reproduce the behavior:
> ```
> 1. In Pock, go to Preferences, Control Center Widget
> 2. Click on "Show Brightness up/down Item"
> 3. Click on Click on "Show Volume up/down Item"
> 4. When you type it on the touch bar, nothing happens
> ```
> 
> **Expected behavior**
> When you type any of the 4 items on the touch bar, you expect that the brightness goes up or down, or that the volume goes up or down.
> 
> **Screenshots**
> <img width="466" alt="Capture d’écran 2019-12-17 à 18 10 41" src="https://user-images.githubusercontent.com/11302315/71018812-7760ce80-20f9-11ea-81f8-c3b9dbec354b.png">
> <img width="1085" alt="Capture d’écran Touch Bar 2019-12-17 à 18 17 04" src="https://user-images.githubusercontent.com/11302315/71018945-bb53d380-20f9-11ea-8875-c656ce4fa501.png">
> 
> 
> **Versions:**
>  - macOS version: 10.15.2
>  - Pock version:  0.7.2
> 

What did u mean by “When you type it in the Touch Bar”?

To my understanding, the options you chose are in Control Center Widget. The default setup doesn’t include this. You can get to it by clicking Pock’s icon in menu bar, choose “Customize…”, then drag the Control Center Widget onto the TouchBar.

**Comment by mediter** [comment]
What did u mean by “When you type it in the Touch Bar”?

To my understanding, the options you chose are in Control Center Widget. The default setup doesn’t include this. You can get to it by clicking Pock’s icon in menu bar, choose “Customize…”, then drag the Control Center Widget onto the TouchBar.

**Comment by monsieursXYZ** [comment]
if you haven't tried this already:
press command c [customize] in pock
drag in what you want
