### ISSUE TITLE
Adjust the sequence of the  widgets in 'Control Center'?

### ISSUE THREAD

**Issue by Mellonlee** [pock/pock#318]
**Describe the feature you'd like to improve in Pock**
user can adjust the sequence of the  widgets in 'Control Center'?

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Jobey-G** [comment]
This would be great!

Would like to move Lock Computer next to Touch ID.

**Comment by CasualDeveloper** [comment]
Same. I also think the Lock Mac button should be placed at the left-most position, right next to Touch ID.
