### ISSUE TITLE
Italian

### ISSUE THREAD

**Issue by fusengine** [pock/pock#321]
Pock have default language italianne? why this is my seconde request
is possible to default language is English?

<img width="474" alt="Capture d’écran 2020-01-05 à 17 37 45" src="https://user-images.githubusercontent.com/7295655/71783113-5d245d00-2fe2-11ea-9611-3cbbe1bf309b.png">

**Comment by L1cardo** [comment]
Do you mean that Pock doesn’t support Italian?

**Comment by fusengine** [comment]
But pock have default language is italian but why you app is not default english?

**Comment by fusengine** [comment]
no reactive
