### ISSUE TITLE
Battery drain under Catalina MacBook Pro 16

### ISSUE THREAD

**Issue by dirtysock** [pock/pock#325]
On my machine Pock is causing 13% of my battery consumption. 
Too much to keep it running. 

Just so you know:)

--- Battery info ---
hasbattery: true
maxcapacity: 8606

--- Graphics info ---
model: Intel UHD Graphics 630
vendor: Intel
videoram: 1536 MB
display_model: 
display_connection: This is laptop
resolutionx: -1
resolutiony: -1

--- System info ---
manufacturer: Apple Inc.
model: MacBookPro16,1
serial: C02ZT8CCMD6R
uuid: FA6DA6ED-25F1-5A05-902E-14C0C7070991

--- Memory info ---
total_memory: 34.36 GB
swaptotal: 2.147 GB

--- OS info ---
platform: darwin
distro: Mac OS X
release: 10.15.2
codename: -
kernel: 19.2.0
arch: x64

--- CPU info ---
manufacturer: Intel®
brand: Core™ i7-9750H
speed_coree: 2.60
cores_count: 12

**Comment by RyanRoberts** [comment]
Same here although mine is showing closer to 20%.

**Comment by kaplanyan** [comment]
Same here.

**Comment by AstraLinger** [comment]
true. mbp16 getting 7 hours with pock. should be around 10 without it.

**Comment by riverrun46** [comment]
I'm using a mbp13 and also have this issue. Actually have to turn pock off when unplugged.

**Comment by AstraLinger** [comment]
by turning "notification badge refresh rate" to "Never" the energy impact of Pock decreased significantly to an acceptable level. so considering turning this feature off to save battery.

**Comment by orthodoX** [comment]
I was keeping the _notification badge refresh rate_ setting to _Instantly_ since I found it so useful, but it's really making Pock as one of my top 3 battery consumers. It would be so nice to have this feature and a decent battery drain at the same time 🤞 🙂

**Comment by juanandresgs** [comment]
Any chance of having different behaviors for when connected to power vs on battery?

**Comment by monsieursXYZ** [comment]
does the developer have an explanation for why it uses 20-50% of a core?

**Comment by Natha** [comment]
Same thing over here, with a 2018 MacBook Pro 15".
I did try it for a whole day, and the energy impact is more than 10 on my Activity Monitor.

I really, really like this app. It's one of the best available around.
Like, it's so simple compared to the mess that are BetterTouchTools scripts.

But, this energy consumption kills it all. :-(

**Comment by fabiand93** [comment]
I'm running it on Mac Big Sur 11.6
and It took the 80% of my battery in less than 2 hours
and on the activity monitor the app stays on 50-70 points of consumption

The issue keeps going.

**Comment by sealvessel** [comment]
I agree, this app perhaps needs better optimization, but it already is… I guess a low battery option would be good. There truly is no point in this application showing the battery status if it makes the battery worse…

**Comment by sealvessel** [comment]
It would be much better if Apple had just made this built in right from the very start with the release of the touchbar laptop… I mean, a touchbar is just a secondary display, and the dock is always shown? I do not understand how emulating the dock onto the touchbar creates performance issues.
