### ISSUE TITLE
Hide music app icon in dock widget when now playing

### ISSUE THREAD

**Issue by matthewdias** [pock/pock#326]
When the now playing widget is shown, and we are not using the buttons only version of it, hide the app that is playing from the dock widget. That way we can remove a redundant app icon from the touchbar.

**Comment by L1cardo** [comment]
I don’t quite understand you.
You can remove the now playing widget through customize menu

**Comment by matthewdias** [comment]
![image-1](https://user-images.githubusercontent.com/3302524/71427022-c28a5c80-2678-11ea-88d4-69aad3d4bf6e.png)
For example, with this proposed option turned on, only one Spotify icon would show here (the one in the now playing widget)

**Comment by L1cardo** [comment]
Left icon is the icon that is on your dock.  Right icon is what playing now. I don’t think showing only one icon is a good idea.

**Comment by matthewdias** [comment]
In my opinion the dock is transient anyway. I get that some people would want to keep consistency tho, which is why I propose this as a configurable option. But if maintainers think it's out of scope then no big deal, I can live with it.

**Comment by L1cardo** [comment]
haha, i am not the maintainers,  i just telling me opinion.
