### ISSUE TITLE
widgets for key-lighting and Siri

### ISSUE THREAD

**Issue by BenjiMandel** [pock/pock#337]
hi,

First, I love Pock its super useful, and I use it since I got my Mac. Thanks for building it!!!

On the regular Touch Bar settings of the Mac, without pock, there is a Siri widget and a widget to control the key lighting, is it possible to add those 2 widgets?

thanks a lot!!
regards,

**Comment by L1cardo** [comment]
I think this will be on along with PockKit, please just wait.

**Comment by BenjiMandel** [comment]
Sure, thanks.
When will it be released?


Verstuurd vanaf mijn iPod
