### ISSUE TITLE
Optional media swipe gestures

### ISSUE THREAD

**Issue by willvousden** [pock/pock#346]
**Describe the feature you'd like to improve in Pock**
Make swipe gestures optional.

For a long time I wondered why sometimes Spotify would skip a track when I tried to pause it.  Turns out there's a swipe feature I wasn't aware of, but after experimenting with it, I can't reliably skip tracks in the direction I want to (and often it skips when I want it to pause).

Unless it can be made more reliable, I'd suggest adding an option to disable it.

**Comment by james10424** [comment]
After playing with the gesture a bit I am pretty sure it's up and down, not left and right. It's hard to perform since there isn't much room to swipe up or down.

**Comment by james10424** [comment]
It seems like you have to swipe within the music widget to trigger the gesture according to PKView in PockKit, there must be a reason for that but it would be nice to add a boolean to let us swipe outside of the widget.

https://github.com/pigigaldi/PockKit/blob/13b84eaac269e69f78a985c9180d6bccb0fe4bf6/PockKit/Sources/PKView.swift#L76
