### ISSUE TITLE
Providing Haptic Feedback while Clicking on Touch Bar

### ISSUE THREAD

**Issue by cecilyen** [pock/pock#347]
**Describe the feature you'd like to have in Pock**
I find it’s nice to have the haptic feedback while clicking on the Touch Bar. 

**Describe alternatives you've considered**
This feature has been implemented in this app. https://github.com/niw/HapticKey But, it will be nice if you can integrate HapticKey's feature in your app. So, there is no need for a separate app.

**Additional context**
I love Pock, which is very handy. I hope Pock can be the only app that every Touch Bar owner will ever need.

**Comment by andreyrd** [comment]
This is still a valid and good request

**Comment by rvlak** [comment]
Yes, it would be really good to add this feature!
