### ISSUE TITLE
Remove virtual esc option

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [pock/pock#351]
Please add an option to remove the virtual esc button for the 16inch macbook

**Comment by ariofrio** [comment]
You can already remove it. Click on the Pock icon in the menu bar and select "Customize...". Then drag the <kbd>esc</kbd> button to the trash can on the left. Voila! No more virtual <kbd>esc</kbd> button.

**Comment by vietqhoang** [comment]
> You can already remove it. Click on the Pock icon in the menu bar and select "Customize...". Then drag the esc button to the trash can on the left. Voila! No more virtual esc button.
> 
> It would probably be good if this was the default on 16-inch MacBooks.

I followed the directions with my MBP 16" and I don't see the trash can. Is it suppose to be on the left side of the Touch Bar?

**Comment by ariofrio** [comment]
Yes. Huh, not sure about MBP 16, I’m on 15’’. Maybe you have to drag it out of the Touch Bar with your mouse on MBP 16?

**Comment by haakonnessjoen** [comment]
I am also unable to remove the esc on MBP 16". It will only move around. Nowhere to put it to get it removed. There is no trash on the left side. And the other trash icon I find does not do anything.

**Comment by Couto** [comment]
Have you tried to drag the icon up? From the touch bar to the laptop display? That worked for me.

**Comment by vietqhoang** [comment]
> Have you tried to drag the icon up? From the touch bar to the laptop display? That worked for me.

This isn’t working for me. This worked on my 15”, but the 16” isn’t allowing the drag up to remove option.

**Comment by donaltuohy** [comment]
Having the same problem here on 16". Can't get the cursor down to the touch bar to drag it up and have no trash can on the left.

**Comment by vietqhoang** [comment]
Should we open a new bug issue since this seems to be more of a bug and not a feature request (feature already exists)?

**Comment by luissantiagodev** [comment]
I'm trying to delete the esc option on the 16" but I can't get the cursor down too

**Comment by luissantiagodev** [comment]
I was able to remove the esc button on the "16 by adding the esc button again and holding the icon for 2-3 seconds an pulling it up with the trackpad.

**Comment by vietqhoang** [comment]
> I was able to remove the esc button on the "16 by adding the esc button again and holding the icon for 2-3 seconds an pulling it up with the trackpad.

This worked for me. I had to follow this method for the other widgets as well.

**Comment by varenc** [comment]
I had trouble getting this to work, but eventually, it was fine.   Sometimes the mouse won't go down into the touch bar

I recommend first opening the Pock preferences, which seems to bring the Pock touch bar items into the correct state, and then click Customize in the Pock menu.  Use your mouse to grab the Esc button and drag it up.

**Comment by rowbawts** [comment]
> I had trouble getting this to work, but eventually, it was fine. Sometimes the mouse won't go down into the touch bar
> 
> I recommend first opening the Pock preferences, which seems to bring the Pock touch bar items into the correct state, and then click Customize in the Pock menu. Use your mouse to grab the Esc button and drag it up.

This solved this issue for me as well with a 16", thanks!
