### ISSUE TITLE
Pock Doesn't actually change the system brightness 

### ISSUE THREAD

**Issue by lordofthewolves** [pock/pock#353]
A simple bug that is that pock fails to properly change the brightness, thus it reverting back to the original setting selected with Mac OS defualt interactions (Touch Bar / system preferences)

**How to reproduce**
Turn **off** _True Tone_ and _auto adjust_ and set brightness to whatever you want and keep the _system settings_ window open to the display tab

Then change brightness using the _SLIDER_ variant of the brightness control in POCK and look at the brightness slider in the _system preferences_ window.

Take note how the slider in _system preferences_ doesn't move and after some time will 'reset' back to the brightness selected in _system preferences_ / stock Touch Bar controls. 

This happens randomly or when _True Tone_ is adjusting, when and **IF** it is on. You can also force the change to happen when you turn on and off _True Tone_.

**Expected behavior**
I expected the brightness slider in system preferences to act accordingly and mimic to what was used on POCK.

**Some video evidence**
*will add later*

**Versions:**
 - macOS version: 10.15.2 Catalina
 - Pock version:  0.7.2

**Comment by scottkuma** [comment]
I am also experiencing this problem on 10.15.2 & Pock v0.7.2.
