### ISSUE TITLE
Auto-hide brightness & volume bar after no use/input

### ISSUE THREAD

**Issue by DanielVolt** [pock/pock#354]
**Describe the feature you'd like to have in Pock**
Pock should auto-hide the brightness and volume bar after 5-10 seconds of idle after input.

**Comment by SerDIDG** [comment]
Also sliders should be draggable without second press, like in system default.

**Comment by trevormeier** [comment]
I'd also love to see this! So many times I look down after 20-30 minutes and the volume slider is still open 😂
