### ISSUE TITLE
使用几小时后touch bar app图标消失 pock程序退出了 恢复到了初始化touch bar

### ISSUE THREAD

**Issue by sharkat** [pock/pock#358]
使用几小时后touch bar app图标消失 pock程序退出了 恢复到了初始化touch bar

**Comment by hufengxiao** [comment]
建议说一下系统版本和软件版本还有机型

**Comment by BenjaminX** [comment]
MacBook Pro (16-inch, 2019)
有遇到

**Comment by Javalover93** [comment]
Pock 0.7.2，macOS Catalina 10.15.3, MacBook Pro (15-inch, 2018)

**Comment by L1cardo** [comment]
没遇到该情况...
