### ISSUE TITLE
Reflect do not disturb state in the control center widget

### ISSUE THREAD

**Issue by jbraem** [pock/pock#359]
Currently the "do not disturb" button works as a toggle in the control center, but there's no way to tell what the state is at a glace.

It would be great if the icon changed to reflect whether do not disturb was enabled or disabled –similar to how the volume & mute icons are updated to reflect their states. 

Perhaps an outlined vs. filled moon icon or something.

**Comment by kianlavi** [comment]
This doesn't solve your issue of checking state via Pock, but macOS reflects the state by dimming the Notification Center icon
<img width="53" alt="image" src="https://user-images.githubusercontent.com/5882434/74770800-d2ba5480-5241-11ea-8786-c7e8db522c79.png">
