### ISSUE TITLE
Can the default group separate the esc button, because the Macbook Pro16 has a physical esm button

### ISSUE THREAD

**Issue by HanMs** [pock/pock#362]
Can the default group separate the esc button, because the Macbook Pro16 has a physical esm button

**Comment by buzzlaker** [comment]
Second this.

**Comment by HanMs** [comment]
v

**Comment by L1cardo** [comment]
you can remove wax key

**Comment by sebo83910** [comment]
How do you then remove this ESC key?

**Comment by L1cardo** [comment]
You can remove ESC button like this
https://gfycat.com/WelllitEquatorialBanteng

**Comment by sebo83910** [comment]
Hi,
This is not working. I don't know if you're using the trackpad but I do and I can't reach the touchbar to click & drag out the ESC button.

**Comment by kriskate** [comment]
try dragging a widget onto the touchbar and you'll be able to select the esc key as described

**Comment by sebo83910** [comment]
Tried it but not successful neither... would be best to have some kind of switch on the configuration menu

**Comment by kriskate** [comment]
for me that's how it worked
Now, after a day of use and no more crashes (it randomly crasged a couple of times), i can just move the mouse to the bottom if the screen and the bar's config acts like the OEM.

![pscr](https://user-images.githubusercontent.com/9143267/76933507-f41c6800-68f5-11ea-8d46-d9bffe361520.png)

**Comment by devmullets** [comment]
> Tried it but not successful neither... would be best to have some kind of switch on the configuration menu

i just did this 'cause i was having the same issue. i just dragged the ESC button down and let go without moving my mouse back up to the screen, then carefully hovered over the ESC button and clicked and dragged it up. 

took me a couple tries to get it to work but now it's good. i do wish that the ESC button wasn't there by default, as well.

**Comment by sebo83910** [comment]
> > Tried it but not successful neither... would be best to have some kind of switch on the configuration menu
> 
> i just did this 'cause i was having the same issue. i just dragged the ESC button down and let go without moving my mouse back up to the screen, then carefully hovered over the ESC button and clicked and dragged it up.
> 
> took me a couple tries to get it to work but now it's good. i do wish that the ESC button wasn't there by default, as well.

Yes!!! that worked! Thanks! Still would be best to have some kind of swiches... but that's cool.
