### ISSUE TITLE
Hi dear devs, there is an annoying problem about the esc key.

### ISSUE THREAD

**Issue by DesmondX** [pock/pock#368]
**Describe the feature you'd like to improve in Pock**
Bigger esc key valid touch area, cover the most left side area where is not able to place your widget. 
Please let the 'esc' key's valid touch space cover all the left side corner, but the key itself stay the same size, just like the original touch bar's 'esc' key. I believe that would make it much easier to press the esc key on the touch bar.

**Describe alternatives you've considered**
Bigger esc key. Or place it at the most left space.

**Additional context**
Pock is a fantastic app. But this problem is really annoying. Hope you could notice this request and hope you are doing well. Much appreciated!

**Comment by angristan** [comment]
I have been meaning to report this too. The original touch bar has a larger `esc` area that spans beyond the virtual `esc` button on the left.

**Comment by pleunv** [comment]
This is indeed extremely annoying. I have to press my escape key twice whenever Pock is active because I keep hitting outside its range, as I'm used to the normal key's range.
