### ISSUE TITLE
Brightness changes by itself

### ISSUE THREAD

**Issue by csrrvl** [pock/pock#371]
Since I installed Pock (which is a great app by the way), the brightness of my screen is changing automatically. 

I have disabled the option of adapting the brightness with the ambient light but it is changing anyway. 

I don't really know why it is happening but it is a little disturbing sometimes. 

thank you in advance for fixing this bug ! I a looking forward seeing some improvments and new features in pock in the future ! 

Good job !!! :) 

**Versions:**
 - macOS Catalina : 10.15.3
 - Pock version:  0.7.2

**Comment by remirr** [comment]
I have the same issue with this - constantly happens with v. 0.7.2 on a 15" MBP 2019

**Comment by keot** [comment]
Possibly fixed by https://github.com/pigigaldi/Pock/pull/357?

**Comment by csrrvl** [comment]
Do you think this will be fixed on next version? 

Cause i tried to understand what is said in #357 but i am not even a web developer and i don't really know how to fix it myself haha 

thank you very much for your help !
