### ISSUE TITLE
Add an Input sources option in Control Center Widget 

### ISSUE THREAD

**Issue by futandrew** [pock/pock#372]
**Describe the feature you'd like to improve in Pock**
Originally, macOS provided a button for changing input sources on the touch bar, this is very useful for users who have more than one keyboard or more than one input language. Hopefully, this feature can be added soon. Thanks. 

**Describe alternatives you've considered**
Add an Input sources option in Control Center Widget

**Comment by okarin001** [comment]
I was going to request this feature. But, I guess I am not the online one. I hope someone adds this in future. That way I can use the globe key for something else.
