### ISSUE TITLE
[Question] How did we get the touchbar to override the existing one and stay there consistently

### ISSUE THREAD

**Issue by vijaykiran225** [pock/pock#373]
Team,
This is more of a question for me understand how the app is designed.

How did you get the touchbar to override the existing one and prevent other apps from disturbing it ?

Could anyone point me to the code, so that i can understand it better ?

Thanks,
Vijay

**Comment by fklement** [comment]
@vijaykiran225 Is pock really permanent on your mac? I need to start it multiple times per day.

**Comment by vijaykiran225** [comment]
im just trying to understand the code  :) 
had few times when pock had to be restarted .. :)
