### ISSUE TITLE
notification badge refresh rate on "instantly" shows red dot on safari icon 

### ISSUE THREAD

**Issue by paffi05** [pock/pock#377]
notification badge refresh rate on "instantly" shows red dot on safari icon, but there isn't any real notification

1. Go to 'preferences' - dock widgets
2. change notification badge refresh rate to "instantly"
3. Red notification badge appears on safari icon

<img width="1004" alt="Touch Bar Bild 2020-03-27 um 15 20 48" src="https://user-images.githubusercontent.com/62714653/77765437-8d5a2580-703e-11ea-9e24-749607824af3.png">

**Screenshots**
`To take a Touch Bar screenshot use the shortcut "shift + cmd + 6"`

**Versions:**
 - macOS version: 10.15.4 
 - Pock version:  0.7.2

**Comment by maltoze** [comment]
Same problem on chrome icon.

<img width="1085" alt="触控栏快照2020-05-24 下午3 45 52" src="https://user-images.githubusercontent.com/18044730/82748578-c19b5980-9dd5-11ea-8eb3-9ed0ddac2787.png">
