### ISSUE TITLE
Handoff items not shown in the dock

### ISSUE THREAD

**Issue by adelowo** [pock/pock#38]
Hi, thanks for this awesome app. 

I just have one tiny request, I sometimes make heavy use of Apple Handoff but ___my handoff app___ isn't displayed on the dock in the touch bar.

Will be really nice if this gets done. Occasions like this are the very few times I have to use the original MacOs dock.

https://support.apple.com/en-ng/guide/mac-help/hand-off-between-devices-mchl732d3c0a/mac

**Comment by pigigaldi** [comment]
This is an awesome idea! I’ll surely keep this in consideration for future releases. 👍🏻
