### ISSUE TITLE
Press close apps + confused Now Playing widget

### ISSUE THREAD

**Issue by Sellig1** [pock/pock#394]
Would it be possible for a future update to include the option to close apps by press-and holding down on it's icon in the touchbar?

The Now Playing widget has trouble switching between Spotify, iTunes and Youtube. If i switch from Spotify or Youtube to iTunes and then back it will display a song from Spotify with the iTunes logo. When i press it it will open iTunes, even if i closed it. 

Please consider these changes. 

Thanks.

**Comment by darshkpatel** [comment]
If someone can point me in the right direction, I'd love to send a PR for the press to close app feature

**Comment by AlecDusheck** [comment]
It would be very cool to get something like this. I'm honestly surprised this hasn't been implemented yet.
