### ISSUE TITLE
Long press and slide to adjust slider

### ISSUE THREAD

**Issue by abhi21git** [pock/pock#400]
To save space on touch bar I replace volume up and down with volume slider, I did same with brightness too.
But one thing which is kinda odd is the slider functionality is different from what it used to be by default.
To adjust the volume I need to first touch slider then move it, while earlier it was just long-press it and drag without lifting finder.
Also, the slider does not hide automatically after some, like I have to close it manually.
I want one more thing while the slider is open tap on blank space should close it instead of just tapping on "x" button.
I am using MacBook Pro 16 (it already have physical ESC key)
macOS version: 10.15.4
Pock version: 0.7.2
![IMG_20200430_135642](https://user-images.githubusercontent.com/42537316/80689454-00960200-8aeb-11ea-905b-75efa44e7c27.jpg)

**Comment by MPLew-is** [comment]
This appears to be a duplicate of #157.
