### ISSUE TITLE
Quit unexpectedly

### ISSUE THREAD

**Issue by donaldzou** [pock/pock#401]
Pock will somehow quit by itself, i'm on MacOS Catalina (Ver 15.4). Not sure why

**Comment by cjshort** [comment]
Experiencing the same 10.15.3

**Comment by donaldzou** [comment]
> Experiencing the same on MacOS 10.15.3 and Pock 0.7.2.

I think might have something to do with app switching, or app switcher, like Context

**Comment by jdkruzr** [comment]
It seems to crash silently, I'm having the same issue. Is it keeping logs somewhere?

**Comment by TKGZ** [comment]
Same here. Just dissapears randomly.

**Comment by nbara** [comment]
Same here. Is pock still being maintained? No commit since january...

**Comment by pigigaldi** [comment]
> Same here. Is pock still being maintained? No commit since january...

Hi! As stated in the README:
> I’m currently migrating all default widgets to make Pock independent from them. At the end of the process, each widget will have its dedicated repo, where you'll be able to open new PRs. I hope to publish the new sources soon alongside PockKit.
> 
> The PRs that are currently opened will be merged manually in the dedicated widget repository
> 
> Thanks for your patience!
