### ISSUE TITLE
No state change on button when Do Not Disturb is turned on

### ISSUE THREAD

**Issue by LucasVanDongen** [pock/pock#403]
**Describe the bug**
The vanilla Touch Bar allows you to add the Do Not Disturb icon. When Do Not Disturb is on, it has a lighter background. Pock has the icon, but does not change the background when I turned the feature on.

**How to reproduce**
```
1. Add Do Not Disturb to the standard Touch Bar items using System Preferences
2. Ensure Control Center is added to Pock
3. Tap the icon to enable Do Not Disturb
4. Observe the icon wasn't updated
```

**Expected behavior**
The icon should have a lighter background

**Versions:**
 - macOS version: 10.15.3
 - Pock version:  0.7.2

**Comment by josuecosta** [comment]
Still the same problem.. Same here :[

**Comment by livitity** [comment]
+1
