### ISSUE TITLE
Pock Automatically Hides Dock on Big Sur

### ISSUE THREAD

**Issue by JTLSound** [pock/pock#425]
**Describe the bug**
Pock will continuously update the System Preference to "Automatically show and hide Dock" when it opens, or when Pock Preferences are changed.

**How to reproduce**
```
1. Run macOS 11.2.1.
2. Open Pock
3. Dock disappears
4. Set option to show Dock in System Preferences
5. Open Pock Preferences
6. Change any option
7. Dock disappears
```

**Expected behavior**
When running macOS version 10.16.x, Pock would respect user choice to show the Dock, and not switch hiding option, allowing for both Pock to run and the Dock to remain constantly onscreen.

**Versions:**
 - macOS version: 11.2.1
 - Pock version:  0.8.1-5
  
**Additional context**
I can understand hiding the Dock when Pock first opens, but there should be an option to keep Pock from constantly hiding the Dock, allowing users the choice to use both Pock and the Dock.

**Comment by pigigaldi** [comment]
Hi!
This repository is related to Pock core application, and not to Dock Widget.
All issues/request for specific widget must be created in dedicated repo (if is not public yet, just wait cause it will be in few days).

Said that, Dock Widget already has an option to not keep hiding system Dock. Please, see the image below for reference:
![Screenshot 2021-02-16 at 17 02 11](https://user-images.githubusercontent.com/422119/108088418-b8939c00-7078-11eb-8a55-19649249c65d.png)

**Comment by LukeXF** [comment]
This has been really bugging me for weeks! I kept opening up apps that I thought might be causing this, I even looked on Pock a bunch of times in its preferences to see if Pock was hiding my dock by default.

I would consider adding something into the overall preferences (perhaps a link to the widget manager) to explain that there are more settings than just what is shown in the image below for an improved user experience. 

I understand the widget manager is a separate system to Pock's preferences, hence why I suggested a link to the widget manager (or a line of text explaining there are more settings than just shown here) as not everyone will know this.

![image](https://user-images.githubusercontent.com/6208873/111081459-57d27480-84fb-11eb-9c11-5ddfbef2acb3.png)

--- 

Also on a separate note regarding auto-hiding of the dock, I think this is quite aggressive behaviour, this could potentially be annoying people who don't realise what is causing this. Maybe you could explain to people the Pock has taken over control of the dock the first time that it is installed (or some other similar approach)?

Great app overall though! Love Pock and how it finally makes my touch bar useful! Keep up the great work!
