### ISSUE TITLE
No widgets after install Pock Apple M1

### ISSUE THREAD

**Issue by General13K7** [pock/pock#426]
Hello. I tried to instal Pock to MacBook Pro M1 MacOS Big Sur 11.2.1. No widgets were installed (standard or any others). Help please.

**Comment by Ronaltn** [comment]
I installed pock 0.8.1-5 in MacBook Pro M1. There is a red dot in the menu item "open widgets manager", but no widget is displayed after clicking in.

**Comment by andymuk** [comment]
Try an older version. I just updated to the latest and had to update a bunch of widgets but appear to be working fine on my M1

**Comment by Ronaltn** [comment]
> Try an older version. I just updated to the latest and had to update a bunch of widgets but appear to be working fine on my M1

Old version (0.8.0-10) is fine.

**Comment by just1ez** [comment]
> Old version (0.8.0-10) is fine.

How i can download a previous version? I didn't find it. Some one can set up a link right here, please?

**Comment by Ronaltn** [comment]
[pock_0_8_0__10.zip](https://github.com/pock/pock/files/6096688/pock_0_8_0__10.zip)

**Comment by japanese-goblinn** [comment]
same for me, installing 0.8.0-10 helped
