### ISSUE TITLE
Pock stops when in screen lock / sleep mode

### ISSUE THREAD

**Issue by thomashrabe** [pock/pock#427]
**Describe the bug**
Pock is gone after sleep mode / screen lock.

**How to reproduce**
```
1. Run pock
2. Wait for screen lock - do not touch anything
3. Log in again
4. See no pock bar but the original
```

**Expected behavior**
Pock still there

**Versions:**
 - macOS version: [e.g. 11.2.1
 - Pock version:  [e.g. 0.8.1-5

**Comment by j0rdsta** [comment]
I'm also able to trigger this when I use the Lock item on the ControlCenter Pock widget, although I have to wait for the screen to sleep and a random amount of time (not sure how long) before Pock disappears. Quite often when this happens Pock will quit completely, but occasionally the system process will still stay open.

**Comment by thomashrabe** [comment]
I do not track how / when it stays alive so it seems it disappears as if it was random...

**Comment by kamusis** [comment]
Exactly the same issue. Not every time, but quite a high chance when wake the M1 MBP from sleep, pock isn't there.

Pock version: 0.8.1-5
macOS: 11.2.1

**Comment by mahmouxd** [comment]
Same as @kamusis I am facing this problem on macOS 11.2.1 with Pock 0.8.1-5

**Comment by donfeng97** [comment]
Looks like this problem happen a lot after updates to macOS 11 from macOS 10

**Comment by mperrien** [comment]
I'm still on macOS 10.15.5 and I experience it too, since updating Pock to 0.8.1-5

**Comment by kamusis** [comment]
This project may not continue to be developed, Apple has deprecated touch bar anyway.

**Comment by blabidu** [comment]
Yep, same problem still. Is there an app that restarts chosen apps after waking up from sleep/lock?

**Comment by bluerxing** [comment]
> Yep, same problem still. Is there an app that restarts chosen apps after waking up from sleep/lock?

double click CTR  after waking up from sleep/lock

**Comment by blabidu** [comment]
> double click CTR after waking up from sleep/lock

What the, does this enable/disable pock? There was a shortcut for this? Are you the developer of Pock?

**Comment by bluerxing** [comment]
> > double click CTR after waking up from sleep/lock
> 
> What the, does this enable/disable pock? There was a shortcut for this? Are you the developer of Pock?

No, I am not the developer, I just try to help you with my experience.
Following is my compromise approach for the similar issues:

"A compromise approach is to double click ctr key when it unexpectly switch to default layout.

By my painful test:

when logout and login in short time. Mac os will reset touchbar to the system dedault layout and Pock don't override system layout (however override with long time logout and login).

It also encounter this situation when unintentionally double click ctr key.

So getting used to Pock' function that double press ctr key to switch system layout and pock layout."

**Comment by Paul-2049** [comment]
I'm still using Pock and this problem still persists. MacOS Ventura. Is there any chance to fix this?
