### ISSUE TITLE
New version of dock widget for Pock crash Pock

### ISSUE THREAD

**Issue by pcnetwizard** [pock/pock#428]
When I try to download the new dock widget, it crashes the pock entirely.  I will have to re-launch pock.  However, the new Dock widget will not get successfully downloaded even if I did Re-Install default widget.  Is there a separate download link that I could download the dock widget directly?

**Comment by downerxl** [comment]
My pock dock widget successfully installed,but the customize of widget shows a bland dock icon,witch is undraggable,os 10.15.7 and os 11.2.1 has the same problem.

**Comment by haakonnessjoen** [comment]
I have the same problem. I just upgraded pock. And it died while it was downloading the default widgets. Now I have no widgets to choose between.

**Comment by tabris233** [comment]
I have the same problem, too. 

I install Dock.dock widget after download https://pock.dev/widgets/defaults/Dock.pock.zip .

Now, I only have one weiget in my pock.

![image](https://user-images.githubusercontent.com/29500388/109406917-d08fe780-79b7-11eb-86eb-e5ae8c2cc502.png)

**Comment by zqcccc** [comment]
https://pock.dev/widgets/defaults/Dock.pock.zip is not the newest version of default dock widget
