### ISSUE TITLE
Pock won't go past Customize button

### ISSUE THREAD

**Issue by dahenson54** [pock/pock#429]
**Describe the bug**
A clear description of what the bug is.

After choosing the buttons on the customize screen, and selecting done, none of the buttons appear. It only shows the Customize button.

**How to reproduce**
```
Unsure how to reproduce.
```

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
`To take a Touch Bar screenshot use the shortcut "shift + cmd + 6"`
<img width="1085" alt="Touch Bar Shot 2021-02-16 at 10 38 17 PM" src="https://user-images.githubusercontent.com/79182715/108152821-dfb59200-70a7-11eb-8400-78b6291105d7.png">

**Crashlog**
If applicable, add crashlog to help me investigate your problem.
``` 
1. Open the Console application located at "Application -> Utilities -> Console.app."
2. Click on "User Reports" in the left menu, then locate the latest Pock crash report. (You can filter reports by typging "pock" into the searchbar on the top)
3. "ctrl + click" on the latest Pock crash report and click on "Reveal in Finder" option, then attach the .crash file in this issue.
```

**Versions:**
 - macOS version: [11.3 Beta]
 - Pock version:  [0.8.1-5]

**Additional context**

**Comment by entozoon** [comment]
+1

**Comment by entozoon** [comment]
Managed to work around it somehow by going into Pock > Advanced > Reinstall default widgets, then Pock > Customise touch bar

**Comment by electblake** [comment]
yeah, no joy here on @entozoon work-around. Will keep experimenting, but pock on Big Sur doesn't work for me yet.

**Comment by entozoon** [comment]
Yeah, even when it does work it'll randomly just vanish from the touch bar, or even close the app every couple hours so it's just doing my head in.

**Comment by lukethomas1** [comment]
+1

**Comment by pleunv** [comment]
Downgraded back to 0.7.2 here, 0.8 seems to be completely non-functional on my machine. Doesn't download any widgets, doesn't displays any docks, just gets stuck on "Customize widgets". I'm guessing local security policies might have something to do with it, not sure.

**Comment by TheCadien** [comment]
+1 had the same bug  v0.8.1-5

**Comment by Bugrakca** [comment]
I found a solution, I think. Go to Advanced -> Re-Install Default Widgets, download it. Then pock asks you to reload. Don't do that. If you reload the pock, widgets disappear. When pock asks to reload, click to pock icon then quit pock. Then open pock, go to the widgets. You will see all the widgets. I solved the problem like this.
