### ISSUE TITLE
No dock widget icon to drag in customize

### ISSUE THREAD

**Issue by JazzXP** [pock/pock#430]
**Describe the bug**
When I go to the customize screen, there is no way to drag the Dock widget to the touchbar. The text shows up, but the area to drag is blank. I'm guessing this is a Big Sur issue (pre-widget version of Pock was fine on Big Sur).

**Expected behavior**
A way to drag the Dock to the touchbar

**Screenshots**
<img width="1680" alt="Screen Shot 2021-02-17 at 5 54 56 pm" src="https://user-images.githubusercontent.com/30512008/108167250-82721d00-7149-11eb-8628-4585268c771d.png">

**Versions:**
 - macOS version: 11.2.1
 - Pock version:  0.8.1-5

**Additional context**
I have tried reinstalling both Pock and the Widgets from scratch. Security settings should be ok as the previous version of Pock was fine.

**Comment by downerxl** [comment]
Same problem in 10.15.7

**Comment by jonathanabennett** [comment]
Same problem. This is a fresh install on a new laptop, but all security settings have been set according the instructions

**Comment by svtagt** [comment]
Same problem in 11.2

**Comment by jacob-lcs** [comment]
Same problem

**Comment by bbarlag** [comment]
Same here on brand new M1 @ 11.2.

**Comment by PSilling** [comment]
Same problem @ 11.1 (fresh install, all permissions should be enabled).

**Comment by pigigaldi** [comment]
Hi! Try following the instructions in this reddit's thread: https://www.reddit.com/r/MacOS/comments/lggk6o/comment/gms2gg2

**Comment by PSilling** [comment]
Thanks, @pigigaldi, the version downgrade helped 👍

**Comment by bbarlag** [comment]
For me too @pigigaldi ! THANKS

**Comment by jonathanabennett** [comment]
This also worked for me.

**Comment by madeofpixels** [comment]
Sadly this didn't work for me. Tried downgrading then upgrading (1.1-8), as well as uninstalling and downloading the latest widget — still not seeing anything that I can drag.

**Comment by jonathanabennett** [comment]
The steps that worked for me were.
1) Uninstall widget.
2) Install widget via the link from the reddit post.
3) Add to the touchbar
4) Upgrade the widget.

Step 3 is the one that has to be done at that exact point in the procedure. Once you upgrade the widget, you can no longer see it in the customization window. So you've got to add it before upgrading.

**Comment by JazzXP** [comment]
Yep, that workaround worked for me. A bit of a mess though.

**Comment by madeofpixels** [comment]
Ahhh, two key points (I was doing incorrectly):

> 2. Install widget via the link from the reddit post.

i) When installing the old widget, _do not_ download the zip file, extract and install via "Drag Widget Here" — Mac OS warned it couldn't "check it for malicious software", and disabled it. From _Open Widgets Manager_, I was immediately prompted to update the widget (don't), which is important because... 

> 3. Add to the touchbar
...
> Step 3 is the one that has to be done at that exact point in the procedure. Once you upgrade the widget, you can no longer see it in the customization window. So you've got to add it before upgrading.

ii) As @jonathanabennett pointed out, you have to customize and drag the old widget onto the touchbar _prior to upgrading it_.

Thanks, works now!
