### ISSUE TITLE
Show Control Strip

### ISSUE THREAD

**Issue by nayrty** [pock/pock#431]
**Describe the bug**
After double pressing the control button to toggle pock, the Control Strip will NOT appear. 

**How to reproduce**
```
1. INABLE Show Control Strip on MacOS in settings
2. Double press Control ^
3. now Control Strip becomes disabled
```

**Expected behavior**
This worked fine in the previous version. The control strip will be DISABLED while using pock, and RESTORE when you double press control. Now, the Control Strip fails to restore. It becomes permanently disabled.

**Versions:**
 - macOS version: 11.12.1
 - Pock version: 0.8-1.5

**Comment by patyiscoding** [comment]
Also experiencing this! Same macOS and Pock versions

**Comment by jic99** [comment]
Also having the same issue on the same versions

**Comment by phara0hcom** [comment]
Also having the same issue on versions:

macOS version: 10.15.7
Pock version: 0.8-1.5

**Comment by ubenik** [comment]
Just to confirm this is also happening to me. More troubling is I have tried to completely remove pock and the built in control strip is not showing up at all.

**Comment by patyiscoding** [comment]
> Just to confirm this is also happening to me. More troubling is I have tried to completely remove pock and the built in control strip is not showing up at all. 

Going to System Preferances > Keyboard and checking 'Show Control Strip' on did it for me. Should work for others too

**Comment by Hovatar** [comment]
Yup, same here. It seems like you can only choose between always having the control strip enabled (even while using the dock on pock) or having it disabled (everywhere, even without pock enabled). I hope they fix it.

**Comment by andymuk** [comment]
Same happening on MacOS Big Sur on M1 Macbook Pro

**Comment by JoeSiu** [comment]
> Going to System Preferences > Keyboard and checking 'Show Control Strip' on did it for me. Should work for others too

Seems only works once for me. If I toggle the pock once again the control strip will reset to the pock's preference (either enable or disable globally)

**Comment by BRadHoc** [comment]
Same problem here macOS 11.2.1 on 2019 Intel MacBook Pro

**Comment by gutaker** [comment]
Same here
MBP M1 16GB 13"
macOS Big Sur 11.2.3

**Comment by ilovecomputers** [comment]
Another offshoot of this bug is when I restart my Mac, the control strip is gone until I toggle the 'Show Control Strip' preference in the system preferences

**Comment by creativecoder** [comment]
Noting that there are now multiple issues open that all seem to be this same problem (Pock turning off the "Show Control Strip" setting in the system Keyboard Preference Pane).

- https://github.com/pock/pock/issues/450
- https://github.com/pock/pock/issues/464
- https://github.com/pock/pock/issues/473
