### ISSUE TITLE
The dock hides automatically despite the settings when you lock the screen

### ISSUE THREAD

**Issue by metelliandrea** [pock/pock#432]
**Describe the bug**
Although in the settings is not set hide system dock, when you lock the screen or suspend the mac, when you turn on the dock is automatically hidden. 

**How to reproduce**
```
1. Open widget manager
2. Remove flag on Hide System Dock
3. Dock is correctly visible on the screen
3. Lock your screen
4. Unlock it
5. Dock is now hidden
```

**Expected behavior**
Locking/Unlocking screen does not change settings

**Versions:**
 - macOS version: 11.2.1
 - Pock version:  0.8.1-5

**Comment by ntatko** [comment]
It also happens on pock reload, or update of the dock widget.

**Comment by PorscheChen** [comment]
Having the same issue here, any get around?

**Comment by tiagosiebler** [comment]
Same issue here just when opening pock...automatically just hides my dock...

**Comment by fregante** [comment]
Run this in terminal to restore your dock if it's not coming back:

```
defaults delete com.apple.Dock autohide-delay
killall Dock 
```

And then in **System Preferences > Dock & Menu Bar** uncheck "Automatically hide and show the Dock"

**Comment by bradydjohnson** [comment]
Ditto. My dock always automatically hides.
