### ISSUE TITLE
Black bar under dock when Pock active

### ISSUE THREAD

**Issue by elykkyle** [pock/pock#433]
**Describe the bug**
When Pock is active, a black bar appears under the MacOS dock.

**How to reproduce**
1. Launch Pock
2. If Pock is active in Touch Bar, observe black bar under dock.

**Expected behavior**
Black bar should not appear, just like when Pock is not active or not running.

**Screenshots**
Pock active:
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/15004488/108533373-83689300-729e-11eb-9a5a-e82aa4a827ad.png">

Pock inactive:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/15004488/108533441-99765380-729e-11eb-95db-d76ba0d08647.png">

**Crashlog**
If applicable, add crashlog to help me investigate your problem.

N/A

**Versions:**
 - macOS version: 11.2.1
 - Pock version:  0.8.1-5

**Additional context**

**Comment by Hovatar** [comment]
This isn't a bug. This feature is enabled/disabled by going to Pock>Open Preferences>Show Tracking Area, under the cursor section. Its just an area to show where you can control pock from using your mouse.

**Comment by elykkyle** [comment]
Ah, yep. that's what it was... Thanks for the education!
