### ISSUE TITLE
Dock won't show on Touch Bar

### ISSUE THREAD

**Issue by SteSanity** [pock/pock#436]
Hey,
I have Pock all installed, it will let me add all the apps in provides but for whatever reason, I still can't seem to get my dock on it. The file is installed but just doesn't seem to show my dock.
I haven't got much experience with Macs in general so any help would be appreciated!

**Comment by uguntde** [comment]
I have the same problem

**Comment by DR-YangLong** [comment]
I have the same problem too!use the 0.7.2 version is ok,but 0.8.15 is not work.mac os x is 10.15

**Comment by sos0** [comment]
Attaching a screenshot:
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/1973082/109411973-4f563780-795a-11eb-932d-8f9456490707.png">

**Comment by sos0** [comment]
I just saw that this is a duplicate of #430.
