### ISSUE TITLE
Pock silently crashing multiple times a day in recent update

### ISSUE THREAD

**Issue by denvermullets** [pock/pock#438]
**Describe the bug**
Pock will silently crash anywhere from 1-3 times a day. Sometimes when my laptop gets woken up, sometimes when I open a new tab in chrome. I've tried reproducing it (the last version would bug out when spotify was open and i had a youtube tab open, sometimes, but this doesn't seem related).

**How to reproduce**
Unsure how to reproduce, see above.

**Expected behavior**
To not crash

**Screenshots**
Here's a shot of my console logs showing crash frequency: https://i.imgur.com/yxs4PRM.png

**Crashlog**
If applicable, add crashlog to help me investigate your problem.
``` 
1. Open the Console application located at "Application -> Utilities -> Console.app."
2. Click on "User Reports" in the left menu, then locate the latest Pock crash report. (You can filter reports by typging "pock" into the searchbar on the top)
3. "ctrl + click" on the latest Pock crash report and click on "Reveal in Finder" option, then attach the .crash file in this issue.
```

[Pock_2021-02-24-071639_Ryans-MacBook-Pro.crash.txt](https://github.com/pock/pock/files/6035937/Pock_2021-02-24-071639_Ryans-MacBook-Pro.crash.txt)

**Versions:**
 - macOS version: [11.2.1]
 - Pock version:  [0.8.1-5]

**Additional context**

**Comment by archcorsair** [comment]
I've noticed the same. I'm having to restart pock multiple times throughout the day

**Comment by cbuijs** [comment]
Same here.

**Comment by sdoering** [comment]
I experience the same behavior. I have to start pick at least two to three times a day.

**Comment by TomWagg** [comment]
Same here.

As far as I can tell it crashes **every time the computer sleeps** for me (i.e. I leave it alone for a while or close the lid) if that helps!

**Comment by panda521119** [comment]
![Uploading WX20210302-113458@2x.png…]()

**Comment by panda521119** [comment]
<img width="841" alt="WX20210302-113458@2x" src="https://user-images.githubusercontent.com/35521314/109593496-0ebe1000-7b4c-11eb-9c80-35d4490e9a75.png">

**Comment by james-antill** [comment]
FWIW I upgraded from 11.0.1? to 11.2.2 and it seems to be crashing much less often, so far.

**Comment by denvermullets** [comment]
> FWIW I upgraded from 11.0.1? to 11.2.2 and it seems to be crashing much less often, so far.

Thanks for the heads up @james-antill, I was on 11.2.1 and will test out this update today.

It's interesting because I do see a connection to Pock crashing after coming back from being asleep, but not always. Really wonder what's triggering it.

**Comment by rfatykhov** [comment]
Crashes all the time
11.2.1

**Comment by mrgoot** [comment]
[pock crash.zip](https://github.com/pock/pock/files/6143556/pock.crash.zip)

More sigbus crashes attached
