### ISSUE TITLE
Pock icon still showing in status bar even after uninstall

### ISSUE THREAD

**Issue by kaylunn15** [pock/pock#439]
**Describe the bug**
Pock stopped working on my MBP last night, shows rainbow wheel when hovering cursor over the icon in status bar. Uninstalled Pock, deleted all files from computer, icon was still there. Reinstalled because I thought that would fix the issue and now I have 2 pock icons in my status bar. 

**Screenshots**
<img width="1080" alt="Screen Shot 2021-02-24 at 11 52 11 AM" src="https://user-images.githubusercontent.com/77954243/109036086-43871e80-7697-11eb-8e2d-d94e27b5b8c2.png">

**Versions:**
 - macOS version: [11.2.1]
 - Pock version:  [ 0.8.1-5]

**Comment by kili77** [comment]
Cant you just click on it and then click on "Quit Pock"

**Comment by kaylunn15** [comment]
> Cant you just click on it and then click on "Quit Pock"

No... Because it shows the rainbow spinning wheel whenever I put my cursor over it and I can’t interact with it at all.
