### ISSUE TITLE
Icons smaller than necessary

### ISSUE THREAD

**Issue by Jeehut** [pock/pock#44]
Currently, the App Icons are smaller than necessary due to the white dot being shown for open apps below them. I don't think that's a good design decision given the small height you have there. It would make much more sense to make the icons as big as possible (using the full height) and indicate open apps in a different way. This way could be:

- the dot could be placed on the left or right, or even at a corner like botom left/right
- open apps could be indicated by a dark gray background color, whilst the current app could have a much more lighter background gray
- the closed apps (without dot as of now) icons could be grayed out (meaning grayscale)

I think it would make sense to add options to the preferences for each of this style, so users can opt for whichever they prefer. For me, I would opt for either the second or third option. I'd need to try them out first to make a final decision.

**Comment by MartijndeHeus** [comment]
I agree. That would be great.

**Comment by pigigaldi** [comment]
I'll definitely take this in consideration for future releases 👍

**Comment by jiegec** [comment]
BTW, I think the spacing between icons should be configurable, because I have lots of apps running and they can't fit into one row.

**Comment by cuneytkaraca** [comment]
Pls  remove me this mail subscript
