### ISSUE TITLE
Found Pock unloaded each time after return from sleep

### ISSUE THREAD

**Issue by idMolotov** [pock/pock#440]
Pock 0.8.1-5

  System Version:	macOS 10.14.6 (18G4032)
  Kernel Version:	Darwin 18.7.0

**Comment by drascotia** [comment]
I am having same issue, attached is my crash log 
[Pock_2021-02-24-171227_Dales-MacBook-Pro.crash.zip](https://github.com/pock/pock/files/6040170/Pock_2021-02-24-171227_Dales-MacBook-Pro.crash.zip)

**Comment by thadjbullet** [comment]
Same issue

**Comment by ALenfant** [comment]
Same issue here!

**Comment by cbuijs** [comment]
Same here

**Comment by samgaw** [comment]
Same issue on Big Sur (M1).

**Comment by eenbeterinternet** [comment]
Same issue here on MacBook Pro 16"

**Comment by idolize** [comment]
Same here on MacBook Pro 16" Catalina 10.15.7

**Comment by andfinally** [comment]
Same issue, same setup as idolize.

**Comment by n8zwn** [comment]
> Same issue on Big Sur (M1).

Same for me.

**Comment by delfuego** [comment]
Same here — not EVERY sleep, but easily more than half of them.

**Comment by ganeshkbalaji** [comment]
Same here.

**Comment by ben-august** [comment]
same for me

**Comment by rabsaris** [comment]
same here.

Versions:
macOS version: 11.2.2
Pock version: 0.8.1-5
Macbook Pro with Apple M1 chip

**Comment by imleean** [comment]
Same here
Version info:
Mac OS: 11.0.1 (20B29)
Pock version: 0.8.1-5
MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)

**Comment by georgeogoodman** [comment]
Same here (not all sleeps, but many/most).
MacOS Big Sur (11.2.3)
1.4 GHz Quad-Core Intel Core i5
MacBookPro15,4
Pock version: 0.8.1-5

**Comment by andfinally** [comment]
Same here. It only started doing this after an update a few months ago.

macOS 10.15.7
MacBook Pro (16-inch, 2019)
Pock version: 0.8.1-5

**Comment by Lefky** [comment]
Same issue

**Comment by leongkui** [comment]
Is this caused by this line: https://github.com/pock/pock/blob/054225c1fe381f248c0af6f4cb6ceca5df9addeb/Pock/AppDelegate.swift#L256
?
