### ISSUE TITLE
There should be an option for keyboard brightness

### ISSUE THREAD

**Issue by Haakenoefstaas** [pock/pock#442]
Pock is a great app, and it looks astonishing. I have one problem, though.
I can't adjust my keyboard brightness, and I would really like to do that. 
I tried to change it in the Control Center, but for some weird reason, that does not work either. 
Therefore, it would be a relief to have keyboard brightness in the ControlCenter widget. 
I really want my keyboard brightness back. Please.

**Comment by eenbeterinternet** [comment]
I second this!

**Comment by marinko-peso** [comment]
Big +, really missing this!

**Comment by IamTheLoki** [comment]
+1 from me too
