### ISSUE TITLE
ControlCenter -> Brightness Toggle Slider not working on M1 Mac

### ISSUE THREAD

**Issue by luispinho** [pock/pock#444]
**Describe the bug**
When the Brightness Toggle is displayed, sliding it has no effect on the actual brightness of the screen. Single pressing on the Brightness buttons works as expected (brightness changes in increments).

**How to reproduce**
Steps to reproduce the behaviour:
```
1. Add the "ControlCenter" widget to the TouchBar;
2. In Widgets Manager, configure this widget to display the Brightness Toggle;
3. Click on the Brightness Toggle. The default value is always 100%;
4. Slide the toggle and see that the actual brightness doesn't change;
```

**Expected behaviour**
The brightness of the screen should change.

**Versions:**
 - macOS version: 11.2.1 
 - Pock version:  0.8.1-5
 - Macbook Pro with Apple M1 chip

**Additional context**
This was tested with the laptop's screen (not with an external monitor).
This might be a similar issue like the one seen in the MonitorControl software, where they have some issues with the Apple M1 chip as well due to some internal software not being available/updated yet to support these new chips.

**Comment by rabsaris** [comment]
My MacBook Pro has the same Trouble.

Versions:
macOS version: 11.2.2
Pock version: 0.8.1-5
Macbook Pro with Apple M1 chip

**Comment by IamTheLoki** [comment]
I can confirm this. Also the Volume Slider is not working...
