### ISSUE TITLE
Touch bar forever stay at 「Add widgets to Pock」> Customize

### ISSUE THREAD

**Issue by mikexjn** [pock/pock#445]
Once I updated to 0.8.1-5

**Comment by mikexjn** [comment]
After i custmized my button on touch bar, it cannot be saved. And touch bar always showed "welcome to Pock"on the right, and 「Add widgets to Pock」> Customize on the left. 

Help MEEEE

**Comment by inksink** [comment]
Me too！

**Comment by mikexjn** [comment]
> Me too！

Still no solution.
Ive been re-installed many times, but no changes

**Comment by opw0011** [comment]
I got the same issue, I just reinstalled back to the old version.

https://pock.dev/download.php?file=pock_0_7_2.zip

**Comment by justinnju** [comment]
Me too

**Comment by mikexjn** [comment]
How to let developer know the issue?

**Comment by drakegens** [comment]
I am also having this issue.

**Comment by dustinlewis** [comment]
Same issue here. MacBook Pro (15-inch, 2019) - macOS Big Sur v11.2.3

**Comment by calmTime** [comment]
Me too, MacBook Pro (16-inch, 2019) - macOS Big Sur 11.0.1 (20B29)

**Comment by 81777268** [comment]
me too

**Comment by iwa** [comment]
having the same issue with the latest version, on MBP 13" M1 :/

**Comment by Alfian5229** [comment]
me too, sadly i like the newest version

**Comment by Alfian5229** [comment]
i got it working everyone, try to reinstall default widget

**Comment by Niksko** [comment]
Specifically, you need to enable Full Disk Access for the widgets to download

**Comment by samuelAle** [comment]
To be even more specific, on Big Sur I had to do the following:

1. Go to `Security & Privacy` settings
2. Click the lock icon to gain privileged system access
3. The lock icon should now be unlocked
3. Go to the Pock toolbar
4. Advanced settings
5. Select `Re-install default widgets`
