### ISSUE TITLE
I want re-install dock widget

### ISSUE THREAD

**Issue by YounggyuKim** [pock/pock#446]
I had issue about dock widget update. When I try to updating dock widget, Pock is frozen.
So, I deleted dock widget. But I can't re-install dock widget. I have to know download link for dock widget.
Can I get to know link?

I installed pock again. But dock widget was equally gone.

**Comment by WristyManchego** [comment]
Same issue here, pock perpetually tells me to update the dock widget, it will never update. Have reinstalled pock many times. Package always fails to install.

**Comment by rudzainy** [comment]
#455
