### ISSUE TITLE
POCK.DEV down

### ISSUE THREAD

**Issue by koubafire** [pock/pock#447]
I cant reach your web to download Pock.

**Comment by pigigaldi** [comment]
OVH had a considerable incident today. SBG-2, where Pock’s website was hosted, is destroyed.
I need to re-host the website on a different provider.
More information about this can be found in this thread:
https://twitter.com/olesovhcom/status/1369478732247932929?s=21

**Comment by koubafire** [comment]
Can you share download link here?

**Comment by pigigaldi** [comment]
You can found the latest versions on [releases](https://github.com/pock/pock/releases) page.
