### ISSUE TITLE
Toggle between original Touch Bar and Pock

### ISSUE THREAD

**Issue by sebastianpulido** [pock/pock#449]
**Description**
- Some times it is convenient to use the options that comes as default with Mac OS.
- It would be great if there is a way to "hide" Pock and display instead the Touch Bar that comes with the Mac.
- Basically add the ability to move between Pock and Touch Bar, probably with "**Command + ~** " ??

**Additional context**
- The progress bar for a video in YouTube is not available as a widget, and it is very useful.
- Turn on/off keyboard backlight is not available as a widget yet, therefore, it would be useful to temporarily move back to the original Touch Bar.

**Comment by maxonlinux** [comment]
Pock already has that feature. Double click the Control button to toggle between them.
