### ISSUE TITLE
Some widgets in the original Touch Bar, not Pock are missing even when Pock is not running or has been uninstalled.

### ISSUE THREAD

**Issue by sebastianpulido** [pock/pock#450]
**Describe the bug**
There are some widgets that comes with the original Touch Bar that are missing since Pock was installed, I apparently there is no way to bring them back

**Expected behavior**
- When closing Pock, there original Touch Bar is there, and there are no missing functions.
- There 4 widgets that never disappear (on the right) no matter what app you are in.. have disappear from the original Touch Bar.

**Versions:**
 - macOS version: Big Sur (MacBook Pro M1)

**Additional context**
Original Touch Bar is missing widget after installing Pock. Uninstalling or closing Pock does not fix it.

**Comment by rheafernandes** [comment]
Same with me... i couldnt find the pock preferences in settings so unistalled it, but there's no change i cant get my orginal touchbar widgets back! Is there any way to reset that. Please help

**Comment by sebastianpulido** [comment]
Yes, you can go every single time to Settings and Enable the control strip or not, but man, if seems more like a bug if you have to do that.... easier if it is enabled again when Pock is not active or running, right?
