### ISSUE TITLE
Volume/brightness sliders occasionally appear

### ISSUE THREAD

**Issue by maxonlinux** [pock/pock#452]
**Describe the bug**
Volume/brightness sliders occasionally appear when pressing the buttons.

**How to reproduce**

1. Open the Pock
2. Press the volume/brightness buttons
3. Slider appears

**Expected behavior**
I expect pressing the button will adjust vol/bright, but sliders occasionally appear instead.

**Screenshots**
N/A

**Crashlog**
N/A 

**Versions:**
 - macOS version: 11.2.3
 - Pock version:  0.8.1-5

**Additional context**
MacBook Pro M1

**Comment by tealshift** [comment]
This is really the only bug that I find annoying about the tool. Otherwise pretty great UX.
The slider is meant to appear after a long press of the volume/brightness buttons, but personally I would like to disable the slider entirely.
