### ISSUE TITLE
Dock widget does not appear once Pock is installed

### ISSUE THREAD

**Issue by SClark70** [pock/pock#455]
Hello,
I have loved Pock but when I tried to install the newest version, I can not get my existing Dock items to appear.

Is the attached screen capture the current version of Preferences pane? When I click the 'customize' blue button on the Touch Bar when running the new version of Pock, I see only the second screen capture. How do I get the Dock' app icons to load in the touch bar? I have set my keyboard setting to show 'App Controls,' and the checkbox to the right indicates 'Show Control Strip.' I am running the latest GA release of Big Sur.

Thank you for suggested next steps.

<img width="482" alt="Pock Preferences screen" src="https://user-images.githubusercontent.com/3931079/111998633-36b8e780-8aea-11eb-9942-3a4e4a19a9cd.png">

![Pock Customize touch bar options](https://user-images.githubusercontent.com/3931079/111998646-3b7d9b80-8aea-11eb-966c-1ee5078988a0.jpg)

**Comment by cgioconda** [comment]
Happening for me as well. Same setup.

**Comment by SeanHood** [comment]
Happened to me too managed to manually install the plugins.

There's a list of the plugins here:
https://pock.dev/api/dev/latestVersions.json

I downloaded each of the .zip files and uncompressed them.

To install: Click Pock menu icon -> Install Widget -> Drag each of the `.pock` files into the window. Then reload Pock and they'll be available.

---

I just discovered Pock this week and I'm loving how minimal it is compared to BetterTouchTool.

**Comment by rudzainy** [comment]
@SeanHood's instructions work for me, except for the dock widget showing empty. still trying to figure this one out 🤔 

<img width="1483" alt="Screenshot 2021-03-29 at 12 48 14 PM" src="https://user-images.githubusercontent.com/13617437/112789162-098eab00-908f-11eb-9f00-3ca04a3d3d16.png">

**Comment by SClark70** [comment]
Sean and Rahman,

I was able to download and unzip each widget but they would not install through the widget manager (using drag and drop or the download hyperlink‘button’ in the widget manager modal dialog.

Thank you for the ongoing research efforts,

Stephen
Sclark1@DecisionMotivators.com

**Comment by rudzainy** [comment]
@SClark70 try copying the widgets manually into `/Users/**your username**/Library/Application Support/Pock/Widgets` folder. After that, restart Pock.

I got some error messages when I restarted Pock after installing the widgets. This popup message comes up for each widget I wanted to install.
<img width="270" alt="Screenshot 2021-03-30 at 8 28 11 AM" src="https://user-images.githubusercontent.com/13617437/112916295-dd2c6a80-9132-11eb-95e0-d5f23cdbf233.png">

So I went into System Preferences > Security & Privacy and click the `Open Anyway` button under General tab.
<img width="672" alt="Screenshot 2021-03-30 at 8 28 37 AM" src="https://user-images.githubusercontent.com/13617437/112916497-3eecd480-9133-11eb-9d1e-7a55acb184f8.png">

I think I had to do a round of clicking the `Open Anyway` button for each widget, restarted Pock, then do another round of the same process.
<img width="266" alt="Screenshot 2021-03-30 at 8 29 02 AM" src="https://user-images.githubusercontent.com/13617437/112917077-83c53b00-9134-11eb-83ab-00b05e2a2d6d.png">

Everything works for me except the Dock widget. Let me know if you have any success with this yah

**Comment by rudzainy** [comment]
the dock widget issue is discussed in #448

**Comment by Jratil** [comment]
https://www.reddit.com/r/MacOS/comments/lggk6o/anyone_else_having_this_issue_with_pock_the_dock/
author suggest in twitter -- twitter link
I have success fix this question by the method. @rudzainy

**Comment by jaydxn1** [comment]
The dock widget bug has been persistently reported by many users with the new update. There is no definitive fix for the issue right now aside from workarounds such as the manual installation of widgets. I recommend installing the previous stable build (v0.7.2) for now until the bugs are fixed. You can find the releases here: [Pock Releases](https://github.com/pock/pock/releases)

In terms of functionalities, there is not much difference between the builds hence you will still get to enjoy using Pock without encountering a myriad of bugs. This is the simplest solution to the problem as of now.
