### ISSUE TITLE
after unistall 

### ISSUE THREAD

**Issue by neorarl** [pock/pock#456]
**after uninstall pock my dock dont apperar or dissapear again**
A clear description of what the bug is.

**after uninstall**
```
1. Go to '...'
2. Click on '....'
3. Scroll to '....'
4. See error
```

****
A clear description of what you expected to happen.

**Screenshots**
`To take a Touch Bar screenshot use the shortcut "shift + cmd + 6"`

**Crashlog**
If applicable, add crashlog to help me investigate your problem.
``` 
1. Open the Console application located at "Application -> Utilities -> Console.app."
2. Click on "User Reports" in the left menu, then locate the latest Pock crash report. (You can filter reports by typging "pock" into the searchbar on the top)
3. "ctrl + click" on the latest Pock crash report and click on "Reveal in Finder" option, then attach the .crash file in this issue.
```

**Versions:**
 - macOS version: [e.g. 10.14.5 (*required)]
 - Pock version:  [e.g. 0.5.2   (*required)]

**Additional context**

**Comment by dualflavor** [comment]
I seem to be having this same issue. Did you get anywhere with this?

After I uninstalled pock, the Dock was initially hidden until I changed the size from system preferences. After doing that, the dock animates to hidden state when enabling the hiding, but doesn't come back on mouse over.

**Comment by dyan33** [comment]
remove ~/Library/Preferences/com.apple.dock.plist rest dock.

> I seem to be having this same issue. Did you get anywhere with this?
> 
> After I uninstalled pock, the Dock was initially hidden until I changed the size from system preferences. After doing that, the dock animates to hidden state when enabling the hiding, but doesn't come back on mouse over.
