### ISSUE TITLE
Weather widget should display temperature

### ISSUE THREAD

**Issue by iank-** [pock/pock#457]
**Describe the feature you'd like to improve in Pock**
It would be great if you could add an option in the weather widget to also display the current temperature in degrees.

**Describe alternatives you've considered**
Couldn't find any 3rd party weather widgets that do this.

**Additional context**
N/A

**Comment by Lefky** [comment]
+1

**Comment by livitity** [comment]
+1

**Comment by livitity** [comment]
+1
