### ISSUE TITLE
Native keyboard control strip disabled after launching pock

### ISSUE THREAD

**Issue by Lefky** [pock/pock#458]
**Describe the bug**
When launching pock or enabling the pock touch bar by double pressing 'control' the native control strip of my mac gets disabled.

**How to reproduce**
```
1. Go to System preferences > keyboard > keyboard
2. Make sure the 'Show control strip' check next to 'Touch bar shows' is enabled
3. Verify you see buttons on the right of your touch bar
4. Launch pock or enable the custom bar by pressing control twice
5. Go back to the native touch bar by stopping pock or pressing control twice
6. Verify you don't see buttons on the right of your touch bar anymore
7. Optionally, got into the keyboard settings again and verify the checkmark is disabled (you need to reopen the view to see the checkmark change)
```

**Expected behavior**
The control strip remains/is again enabled.

**Screenshots**
`To take a Touch Bar screenshot use the shortcut "shift + cmd + 6"`
<img width="1085" alt="Touch Bar Shot 2021-03-24 at 14 48 56" src="https://user-images.githubusercontent.com/10397178/112321209-1175d600-8cb0-11eb-962f-cb6a1d38c967.png">

<img width="659" alt="Screenshot 2021-03-24 at 14 48 16" src="https://user-images.githubusercontent.com/10397178/112321130-fa36e880-8caf-11eb-810b-3b7bbce1a989.png">

<img width="1085" alt="Touch Bar Shot 2021-03-24 at 14 49 20" src="https://user-images.githubusercontent.com/10397178/112321257-1f2b5b80-8cb0-11eb-9b77-706d00218115.png">

**Versions:**
 - macOS version: 11.2.3
 - Pock version: 0.8.1-5

**Comment by kili77** [comment]
I have this issue too

**Comment by OliverRH** [comment]
Same issue for me.. :(
