### ISSUE TITLE
Add Screenshot to Available shortcuts in Pock

### ISSUE THREAD

**Issue by MatthewWagnerPEP** [pock/pock#459]
**Describe the feature you'd like to improve in Pock**
The default touchbar has an screenshot shortcut icon that can be added to the dock. This is native in Mac OS X. It would be wonderful to be able to add that to my pock default dock.

**Describe alternatives you've considered**
I can use the keyboard shortcut, but after adopting pock so much it would be much more intuitive for me to go to the touchbar to take a screenshot.

**Comment by livitity** [comment]
+1
