### ISSUE TITLE
Black bar showing up at the bottom of the screen when Pock is open

### ISSUE THREAD

**Issue by sholdensmith** [pock/pock#461]
**Describe the bug**
When I open Pock, a black bar shows up at the bottom of the screen.

**How to reproduce**
```
1. open Pock
```

**Expected behavior**
Not having any artifacts on-screen.

**Screenshots**
`To take a Touch Bar screenshot use the shortcut "shift + cmd + 6"`
<img width="1552" alt="Screen Shot 2021-04-04 at 11 10 00 AM" src="https://user-images.githubusercontent.com/8879504/113517721-a3929f80-9536-11eb-988e-cc49d73d1953.png">

**Versions:**
 - macOS version: [e.g. 11.2.3 (*required)]
 - Pock version:  [e.g. 0.8.1-5   (*required)]

**Comment by jQwotos** [comment]
On my end, it seems to only occur when `mouse support` is enabled.
![image](https://user-images.githubusercontent.com/15173247/113648393-8c4cd280-965a-11eb-972a-1623e6f04f53.png)
_Without Mouse Support enabled_

![image](https://user-images.githubusercontent.com/15173247/113648553-c61dd900-965a-11eb-9d85-6fbd6f713a08.png)
_With Mouse Support enabled_

**Comment by kili77** [comment]
If u have the option "Mouse Support" activated you can uncheck the box next to "Show Tracking Area" then the black are should go away :)

**Comment by sholdensmith** [comment]
It worked! Thank you!
