### ISSUE TITLE
"Show Control Strip"

### ISSUE THREAD

**Issue by kili77** [pock/pock#464]
Im writing because I want to report a bug of the new Pock version (or maybe it is related to the new BigSur 11.2.1 idk)..... but in the system preferences when you go to "Keyboard" there is the section "Touchbar Shows" and there you can activate the Control Strip by checking the box next to "Show Control Strip".... now when I switch to the Pock-TouchBar (by double pressing the control-key) and then come back (by double pressing control again) this feature automatically gets deactivated (somehow the box left to "Show Control Strip" is still checked but the Control Strip doesnt show up on the touchbar like if it was unchecked).... so everytime i switch back from Pock to the normal Touchbar I have to go to preferences and reactivate this, id say necesarry, feature to bring back my controls for brightness ect..... so this is very annoying, and it would be great if you could fix this soon... thx :)

```
1. Go to 'System Preferences' and to "Keyboard"
2. Activate 'Show Control Strip' under 'TouchBar Shows'
3. Activate Pock by double pressing the 'Control' - Key
4. Deactivate Pock by double pressing the 'Control' - Key again
5. See Error: No Control Strip Visible and therefore usable
```

Normally the Control Srip should still show up after deactivating Pock (by double pressing the 'Control' - Key) and it also did in earlier versions of Pock

Versions:
 - macOS version: BigSur 11.2.3 (Problem exists since BigSur 11.2.1)
 - Pock version: 0.8.1-5

**Comment by OliverRH** [comment]
I have the exact same problem, and it is annoying when pock sometimes crashes and then I can't control the volume before starting pock again. Sometimes the touchbar is just all black. But it is worth it, just to use pock.
