### ISSUE TITLE
Launch at login doesnt work

### ISSUE THREAD

**Issue by Warden626** [pock/pock#465]
Currently running MacOS BigSur 11.23, Pock 0.8.1-5 the launch at login feature isn’t working. Every time I tried to apply it the app close by itself but the box is already tick. however every time I restart or turn on the Mac pock Touch Bar doesn't start automatically so I have to open it manually and when I checked preferences launch at login doesn't tick again. 

does someone know how to fix this ?

sorry for my English anyway

Thanks

**Comment by keepchen** [comment]
You can following below steps:
1.Move `Pock.app` to `/Applications` directory
2.Set login item manually -> [reference](https://support.apple.com/zh-cn/guide/mac-help/mh15189/mac)

It works fine on Mac Monterey.
Hope to help.
