### ISSUE TITLE
I cann't add "Dock" widget in Touch Bar

### ISSUE THREAD

**Issue by LyuShiWang** [pock/pock#469]
**Describe the bug**
When I enter "Customize Touch Bar", I cannot drag "Dock" widget in Touch Bar, I can only see the "Dock" title but not see the icon, while other widgets, such as "Status" "ControlCenter" "Weather" "Now Playing" "Esc", have no problem. Can someone tell me why, and how to fix it? thanks.

**How to reproduce**
1.Click on 'Customize Touch Bar'
2.See error

**Expected behavior**
I hope the 'Dock' widget can use normally, or I have to use the old version, Pock 072

**Screenshots**
![Xnip2021-04-21_16-39-41](https://user-images.githubusercontent.com/27322715/115525878-15eada00-a2c2-11eb-8f29-a3c23544e025.jpg)
![IMG_4174](https://user-images.githubusercontent.com/27322715/115526228-65c9a100-a2c2-11eb-8417-9adfd90c4a98.JPG)

**Versions:**
 - macOS version: [Big Sur 11.2.3 M1]
 - Pock version:  [0.8.1-5]
![Xnip2021-04-21_16-42-08](https://user-images.githubusercontent.com/27322715/115526518-b2ad7780-a2c2-11eb-80cc-b6f3a1dc395b.jpg)

**Comment by JazzXP** [comment]
I had the same issue, current solution is to downgrade, add, then upgrade (ugh)

https://github.com/pock/pock/issues/430

**Comment by LyuShiWang** [comment]
> I had the same issue, current solution is to downgrade, add, then upgrade (ugh)
> 
> #430

i do like you said, and it worked! thank you bro

**Comment by PhilippVujic** [comment]
Clicking on Advanced → Re-install default Widgets solved it for me.

**Comment by yugoslavskiy** [comment]
> Clicking on Advanced → Re-install default Widgets solved it for me.

**Comment by ntragic** [comment]
> Clicking on Advanced → Re-install default Widgets solved it for me.

IMO, after re-install, then configure the dock widget before update the dock widget. It worked for me.

**Comment by mediter** [comment]
the issue seems to be caused by Dock widget 1.1-8
