### ISSUE TITLE
Not working: Control strip Configuration: Touch bar shows: "App Controls" & Press and hold Fn key to "Show F1, F2, etc. Keys"

### ISSUE THREAD

**Issue by balanco** [pock/pock#470]
**The bug**
In the "Keyboard" System Preferences, my configuration is:

- Touch bar shows: `App Controls`  (and `Show Control Strip` is _deselected_)
- Press Fn key to:  `Show Emoji & Symbols`
- Press and hold Fn key to: `Show F1, F2, etc. Keys`

The bug: Upon installation of pock or any changes to its configuration, holding the Fn key does _not_ toggle to the Control strip to show the Function keys, but to a _blank_ Control strip.

**How to reproduce**
```
1. Configure the "Keyboard" system preferences as described at the beginning of this posting.
2. From the pock menu in the menu bar, select "Customize Touch Bar…"
3. Click "Done" (i.e., no need to actually change anything)
4. See error: The Control strip now shows the selected pock widgets, but
    holding Fn results in a _blank_ Control strip, rather than showing the function keys.
```

**Expected behavior**
Holding the "Fn" key should show the Function key strip (F1, F2, ...)

**The solution kludge**
```
1. In the "Keyboard" System Preferences,
   change  the configuration of "Touch bar shows:" to `F1, F2, etc. Keys`
   --- the value of "Press and hold Fn key to:" is automagically updated to "Show App Controls",
        and  the Control strip is immediately updated accordingly.
2. _Immediately_  (i.e.: _no_ interaction with the control strip is necessary!) "undo" step 1.,
    i.e.: change the setting of "Touch bar shows:" back to "Show App Controls"
    --- the setting of "Press and hold Fn key to:" is automagically reverted to `Show F1, F2, etc. Keys.`, 
          and the Control strip displays the pock widgets again.
```
==> holding the Fn key now correctly toggles the Control strip to show the `F1, F2, etc. Keys`.

**Screenshots**
(does not apply)

**Crashlog**
(does not apply)

**Versions:**
 - macOS version: Big Sur 11.2.3 (20D91)
 - Pock version:  0.8.1-5

**Additional context**
 - also installed: Haptic Touch Bar 2.4.0 (https://www.haptictouchbar.com/ visited 2021-04-23)

**Comment by alexpts** [comment]
Same problem. Pock overrides the system configuration.
