### ISSUE TITLE
control strip remains hidden when switching to system Touch Bar

### ISSUE THREAD

**Issue by paffi05** [pock/pock#473]
control strip remains hidden when switching to system Touch Bar, even when the box "show control strip" in  system preferences is checked.

**How to reproduce**
```
1. Go to 'system preferences' 'keyboard'
2. Click on 'show control strip'
3. open Pock, hide control strip in pock preferences
4. See error when switching back to system Touch Bar
```

**Expected behavior**
Control strip only should be hidden while pock touchbar is active 
 
**Versions:**
 - macOS version: macOS 11.4 (20F5046g)
 - Pock version:  0.8.1-5

**Comment by gutaker** [comment]
Still same behavior for 0.9.0-22 version :/
