### ISSUE TITLE
[Feature Request] add stock widget

### ISSUE THREAD

**Issue by Junyi-99** [pock/pock#476]
**Describe the feature you'd like to have in Pock**
I would like to suggest that it would be better to have a stock widget.
Therefore we can see the stock values in Touch Bar.

or maybe we can add Bitcoin/ETH price in this widget

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by timrijkse** [comment]
I am waiting for the 3rd party feature to be available. Then I'd like to give the crypto widget a shot :)
