### ISSUE TITLE
Stock touch-bar options missing.

### ISSUE THREAD

**Issue by WiehanVanNiekerk** [pock/pock#479]
**Describe the bug**
After installing pock and all of the plug-ins my original touch bar action options have disappeared. I did update all of my os and delete pock and the issue still occurred. Like the package corrupt the original dock file or something, because I can set it in the customise screen but when done nothing is showing on my touch bar.

**How to reproduce**
Steps to reproduce the behaviour:
- Installed pock 
- Run pock and stop it
- Actions missing from the touch bar.

**Screenshots**
Touch bar in edit mode
<img width="1085" alt="Touch Bar Shot 2021-05-30 at 11 27 27" src="https://user-images.githubusercontent.com/53100080/120099129-25b7d280-c13a-11eb-856b-791e92af11f3.png">
Touch bar on finder
<img width="1085" alt="Touch Bar Shot 2021-05-30 at 11 27 04" src="https://user-images.githubusercontent.com/53100080/120099133-2badb380-c13a-11eb-9d5b-acd43d3c38ac.png">

**Versions:**
 - macOS version: [11.3]
 - Pock version:  [0.8.1-5]

**Comment by jamesogrant** [comment]
I had the same issue. To fix it:

- Open Pock > Open Widget Manager...
- Click Dock
- Update to the latest Dock widget (1.1-8)
- Click "Enable System Dock"
- The system dock should re-appear!

**Comment by jamesogrant** [comment]
Ah sorry, my issue was different (the system dock disappearing).

**Comment by EimisM** [comment]
The same happened to me, I had to go to Pock Preferences and uncheck the "Disable Control Strip" box. Then it brings back the original buttons. After you set this up, you can customize it by heading to your mac keyboard settings and customizing the touch bar.
