### ISSUE TITLE
Brightness toggle not working

### ISSUE THREAD

**Issue by usmandroid** [pock/pock#483]
**Describe the bug**
When using the brightness toggle to change the brightness, it has no effect on the actual brightness of the screen. Whereas if you use the brightness up or down item, the brightness does changes.

**How to reproduce**
```
1. Go to 'touchbar control centre widget"
2. Click on 'brightness toggle'
3. Scroll to 'increase or decrease the brightness'
4. See error: no change in screen brightness
```

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
`To take a Touch Bar screenshot use the shortcut "shift + cmd + 6"`
![image](https://user-images.githubusercontent.com/29359746/120924385-d8a4a500-c6d3-11eb-9338-d21da2e395ed.png)

**Crashlog**
If applicable, add crashlog to help me investigate your problem.
``` 
1. Open the Console application located at "Application -> Utilities -> Console.app."
2. Click on "User Reports" in the left menu, then locate the latest Pock crash report. (You can filter reports by typging "pock" into the searchbar on the top)
3. "ctrl + click" on the latest Pock crash report and click on "Reveal in Finder" option, then attach the .crash file in this issue.
```

**Versions:**
 - macOS version: [e.g. 11.4 (20F71)]
 - Pock version:  [0.8.1-5]

**Additional context**
Using the apple macbook pro 2020 with M1

**Comment by thebrightbulb** [comment]
Commenting here to report same issue. Moving the brightness slider doesn't actually change screen brightness at all.

**Comment by janwedershoven** [comment]
The workaround is, to press the Icon on the left or right side of the slider.
