### ISSUE TITLE
No widgets found

### ISSUE THREAD

**Issue by nesporfilip** [pock/pock#484]
I've installed fresh new installation but I didn't see any widgets. So the app is not ready to be delivered to users...

**Comment by danhrahal** [comment]
I'm having the same problem. I'm here because I was checking if they were available for download. All I have are the default Mac OS widgets.

**Comment by januarfonti** [comment]
![image](https://user-images.githubusercontent.com/5006571/121706083-7e567a80-caff-11eb-990f-7a92c3d3c809.png)

I got a same problem and I did `re-install default widgets` and it works again.

**Comment by mccannt** [comment]
I am facing this same issue :( 

MacOS 11.4 (20F71) / Big Sur

**Comment by nickmanderfield** [comment]
> I am facing this same issue :(
> 
> MacOS 11.4 (20F71) / Big Sur

Make sure you have Pock enabled for 'Accessibility' in Security & Privacy System Settings, then go to the 'Re-install default widgets' as screenshotted above. This fixed my problem as I didn't enable access during original install.

**Comment by mccannt** [comment]
Thanks for the tip @nickmanderfield 

I was able to solve this by downgrading the version of Pock, installing the widgets and getting them configured and then upgrading. Weird but it made it work :)
