### ISSUE TITLE
Small black bar showing up when Pock enabled

### ISSUE THREAD

**Issue by robertspin** [pock/pock#487]
**Describe the bug**
There's a thin small black bar showing up when Pock is enabled. When disabled (double click ctrl), it disappears. 

**How to reproduce**
1. Enable Pock.

**Expected behavior**
There should not be a black bar when Pock is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/86300538/122921483-d5134e00-d362-11eb-9fb3-209f43b70a49.png)

**Versions:**
 - macOS version: 11.4
 - Pock version:  0.8.1-5

**Additional context**
This problem started showing up about 2 months ago.

**Comment by rishabh-ink** [comment]
I can confirm that I see the same on my desktop (see screenshot below).

🩹 **Workaround:** It disappears when I uncheck the **Enable mouse support** checkbox under **Pock ❯ Open Preferences... ❯ Cursor Options**.

<img width="100%" alt="Screenshot of my desktop showing a black bar in the bottom of the screen" src="https://user-images.githubusercontent.com/342789/126310952-55eca578-8f86-4f8e-b56e-f7e695fcf494.png">

**Comment by MonsterZUO** [comment]
also appear on my Mac(ver 11.0.1)
