### ISSUE TITLE
Disabling control strip when pock it open

### ISSUE THREAD

**Issue by daydou55** [pock/pock#488]
When I activate the option Disable Control Strip, it disable it for all.
That means when I double press " ^ control ", the control strip disappears. 
I don't know if it's a Bug or a volontee. But if it's possible to re-activate it when I double press " ^ control " that will be cool

**Screenshots**
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/86422396/123286584-522ef680-d50e-11eb-833d-9c329d6a0d8c.png">

**Versions:**
 - macOS version: [11.4]
 - Pock version:  [  0.8.1-5]

**Comment by l782993610** [comment]
I have the same problem. It makes me unable to use the original toolbar. So that something like screenshoot can't be used.

**Comment by paffi05** [comment]
same issue here

MacBook Pro 
MacOS 11.5 beta
Pock: 0.8.1-5
