### ISSUE TITLE
After uninstall pock, why can not restore the dock?

### ISSUE THREAD

**Issue by gottayan** [pock/pock#489]
<img width="1004" alt="触控栏快照2021-07-02 上午10 39 47" src="https://user-images.githubusercontent.com/23098167/124212682-f7a32500-db21-11eb-99d1-324ae6d8f325.png">

**Comment by HerrTiSo** [comment]
Can confirm - my vanilla touchbar is basically gone.

Steps I tried without success:
- Deleting everything Pock-related and "Relaunched the Touch Bar Agent" beforehands
- Rebooting the Macbook
- Clear the NVRam
- Reset the SMC

Pock needs urgently an uninstaller, to be honest. Thanks in advance!

**Comment by charliekmcmahon** [comment]
I can also confirm this issue - even after completely removing all traces of the app from my system the vanilla touchbar is still missing. Also, even though I delete the pock .app directory, somehow my previous pock config persists through a reinstall. Where is this config stored and how can I purge it? 

I definitely agree Pock needs an uninstaller to remove all traces and preferences from the system.

**Comment by charliekmcmahon** [comment]
@HerrTiSo @gottayan 
I've just found a solution to restore access to the control strip of the touch bar is to go to 
**System Preferences > Keyboard > Check "Show Control Strip"**
This fixed it for me.

**Comment by WhitePuffer** [comment]
> @HerrTiSo @gottayan
> I've just found a solution to restore access to the control strip of the touch bar is to go to
> **System Preferences > Keyboard > Check "Show Control Strip"**
> This fixed it for me.

It works! Thanks!
