### ISSUE TITLE
System Dock appears even if its disabled, when a window is fullscreen.

### ISSUE THREAD

**Issue by ViRo3** [pock/pock#490]
**Describe the bug**
System Dock appears even when it's disabled when a window is fullscreen.

**How to reproduce**
```
1. Go to Widgets Manager
2. Click on Dock
3. Toggle to 'Hide System Dock'
4. Open a window in full screen
5. Push cursor to bottom edge of screen
6. System Dock appears
```

**Expected behavior**
It's expected to not appear since its already in touch bar and disabled system wide.

**Screenshots**
none

**Crashlog**
none

**Versions:**
 - macOS version: [12.0 Beta (21A5268h)]
 - Pock version:  [0.8.1-5]

**Additional context**
None

**Comment by pigigaldi** [comment]
Hi! You need to click on `"Disable System Dock"` button from the Dock Widget preference pane to achieve your needs, only hiding is not sufficient since this option follows the system behavior (`Automatically Show/Hide Dock`) 👍🏻
