### ISSUE TITLE
Haptic Feedback on interaction with widgets of Pock

### ISSUE THREAD

**Issue by ViRo3** [pock/pock#492]
**Describe the feature you'd like to have in Pock**
Integrate [Haptic Feedback](https://github.com/niw/HapticKey) into Pock for use with widgets and buttons
**Describe alternatives you've considered**
Gives TouchBar a much-needed QoL improvement.
**Additional context**
none

**Comment by adx74** [comment]
such a good idea!

**Comment by AliAkinK** [comment]
Clever.
