### ISSUE TITLE
always show the "Add widgets to Pock"

### ISSUE THREAD

**Issue by lancerXXXX** [pock/pock#495]
1. welcome to Pock   -------------- Add widgets to Pock > Customize
2. Customize
3. ok
4. welcome to Pock   -------------- Add widgets to Pock > Customize

so it always show " welcome to Pock   -------------- Add widgets to Pock > Customize " 

**Versions:**
 - macOS version: [11.4 (*required)]
 - Pock version:  [e.g. 0.8.1-5   (*required)]

**Comment by lancerXXXX** [comment]
I tried to reinstall widget
it works now

**Comment by notFoundTheGuy** [comment]
me too
