### ISSUE TITLE
Pock generates a black bar at the bottom of the screen, how do I remove it?

### ISSUE THREAD

**Issue by chuyun** [pock/pock#499]
**Describe the bug**
Pock generates a black bar at the bottom of the screen, how do I remove it?

**Screenshots**
![image](https://user-images.githubusercontent.com/19328403/127257226-833713a2-1286-4f66-b9b6-69f9e652530d.png)

**Versions:**
 - macOS version: [11.4 (20F71)(*required)]
 - Pock version:  [0.8.1-5   (*required)]

**Comment by pigigaldi** [comment]
Just uncheck the "Show tracking area" option :)
![](https://pock.app/_nuxt/img/preference_general.5b99752.png)
