### ISSUE TITLE
Terrible input delay when clicking on the control buttons (brightness and volume adjuster)

### ISSUE THREAD

**Issue by qbfinest1** [pock/pock#502]
When adjusting brightness and volume, (the two most things I actively use on Pock) theres a delay and and the screen freezes a bit when it applies the action. It's even worse when you click on it repeatedly as each input subsequently lags and ends up freezing the computer much longer. Good example is whenever I'm watching a video and I decide to adjust the volume by 3-4 bars, the screen/video will pretty much freeze for 2-3 seconds until the input is finally applied. In other words I believe the input has a bad delay and this started happening since I updated to the latest update OSX 11.5 Big Sur. Before the input was perfect and responded instantly with no delay when pressed. Seems to be exclusive to the brightness and volume adjuster. Other aspects such as pressing on apps and media controls work fine. 

Am running the latest Mac OSX version and Pock version as of this date. Am using a Intel version of the Macbook if that makes a difference. Apologies as I'm not that tech oriented but this app has been pretty useful for my use cases and would like for it to run smoothly again

**Comment by easp** [comment]
How is it with the 11.5.2 update that was released a day or two ago? 11.5.1 introduced some serious lag problems with media controls that seem to be fixed in 11.5.2.

**Comment by qbfinest1** [comment]
Just updated and it got fixed, realized a bit after making the bug post that it was also lagging with the default media controls so assuming it was an system issue and not the app. Thanks for the input!
