### ISSUE TITLE
APP-Crash after update to 0.9

### ISSUE THREAD

**Issue by janwedershoven** [pock/pock#506]
Hey there,

I just upgraded to Pock 0.9 on my MacBook Pro (13-inch, M1, 2020) and Pock won't start.

**Describe the bug**
After start up, the touchbar shows the now playing, control center and status widget then freezes and then chrashes.
While doing that, I'm missing the dock widget and the macOS Control Center is still present.

**Crash-LOG**
[Pock-Crash.log](https://github.com/pock/pock/files/7014837/Pock-Crash.log)

**Comment by ben-august** [comment]
+1
