### ISSUE TITLE
Pock always override the touchbar without pressing Control twice

### ISSUE THREAD

**Issue by rperez93** [pock/pock#507]
**Describe the bug**
Since the update  0.9.0-22 pock is always overriding the touchbar when certain amount of time happens instead of the old nice behaviour of double tap the control key.

**How to reproduce**
```
1. Open Pock
2. Wait until you touch bar go to sleep / or navigate through the system or different apps for about 5 mins
3. Pock will be opened instead of system touchbar
```

**Expected behavior**
Pock should not be opened in my touch bar unless I tap twice the control key (in the previous versions worked that way)

**Versions:**
 - macOS version: 11.5.2
 - Pock version:  0.9.0-22

**Comment by mclate** [comment]
Happens on mac 10.15.7 as well. No need to wait - looks like Pock will override default touch bar without letting the system one to show up. Double `^Control` doesn't work (it doesn't do anything). It doesn't matter what option one selects in "Default TouchBar shows: " setting.

Weird. As i was writing this, touchbar went from pock to the default one and double ^Control started working... Don't know what can cause that.... Thought i'll leave my comment any way - maybe it'll help to investigate.

**Comment by mikozee** [comment]
I discovered something by accident. I think the double control only works if you hold the control button on your second press. So it is press, press+hold to make it work. It wasn't like this in the version .72 where it was merely just two quick presses.

**Comment by rperez93** [comment]
@mikozee but that not solve the problem of pock being active without any interaction every 'X' amount of time

**Comment by mikozee** [comment]
> @mikozee but that not solve the problem of pock being active without any interaction every 'X' amount of time

I'm just saying there might be a glitch affecting how the "other" Touch Bar gets activated because even the key press has been changed.

Plus the issues with the control key press activation was conflated in your issue.

**Comment by seiyria** [comment]
I think I'm having this issue as well. Upgraded pock to stop the crashing, now the bar I set changes to the system one automatically, seemingly at random.

**Comment by AliAkinK** [comment]
I actually have this problem in reverse. I prefer to have Pock open all the time, but after idle time it will revert to default system touchbar without me pressing control twice.
