### ISSUE TITLE
There should be more cities/towns available in the weather widget

### ISSUE THREAD

**Issue by Jarboer** [pock/pock#510]
**Describe the feature you'd like to have in Pock**
The weather widget doesn't have any cities close enough to me and since there's no option for an automatic location, at least as far as I can see, I'm out of luck. The locations that are closest to me are in Ontario, Canada, they are either Stratford, Sebringville, or Rostock. It's also missing a bunch of other cities or towns near me and anywhere else for that matter.

**Describe alternatives you've considered**
For now, I just won't use the widget since it's not worth being completely off in temperature and condition outside.

**Comment by paffi05** [comment]
Still need automatic location for the weather widget!

**Comment by Jarboer** [comment]
This is still an on going limitation.
