### ISSUE TITLE
Pock requests screen recording access for no reason

### ISSUE THREAD

**Issue by Ogerets** [pock/pock#511]
**Describe the bug**
Pock requests screen recording access. Wtf?

**How to reproduce**
I opened settings from touch bar, but it could be random

**Versions:**
 - macOS version: 11.5.1
 - Pock version:  0.9.0 (22)

**Comment by janwedershoven** [comment]
This is used to generate small thumbnails, as seen in README.
If you click on "safari" in your dock, you can switch between tabs.

There is a privacy disclaimer about that somewhere in README or website.

**Comment by Ogerets** [comment]
It still looks weird to me this feature is enabled by default, considering potentially privacy issues. Explanation with "promise" not to record screen is hidden under the link in Readme. And there's no tag for latest release from website, so I'm unable to check that promise.
