### ISSUE TITLE
Control+Command leads to Switch between original TouchBar and Pock

### ISSUE THREAD

**Issue by dull-bird** [pock/pock#514]
It seems a bug to me that when I click Control+Command, the switch will be toggled. The standard shortcut double control also works. The toggle by Control+Command is quite annoying since many other shortcuts have these two keys.

macOS 11.5.2

**Comment by richardso21** [comment]
If I remember correctly, this behavior worked properly on my machine before the 0.9 Pock rewrite. I'm thinking if we just use the previous `HotKey.swift` implementation, it will resolve this issue.
