### ISSUE TITLE
How do you make the nowplaying widget?

### ISSUE THREAD

**Issue by theofficialgrand1** [pock/pock#516]
I'm trying to make a script to get text from the mac now playing widget and couldn't find a way. Then I remembered pock had a nowplaying widget. Didn't know where to ask.

**Comment by pigigaldi** [comment]
Hi! You can find the source code of the Now Playing Widget in its dedicated repo [here](https://github.com/pock/now-playing-widget).
Please note that, to properly get media information, you need to refer to the MediaRemote private framework. Some useful information on how to use this framework can be found in this [StackOverflow thread](https://stackoverflow.com/questions/61003379/how-to-get-currently-playing-song-on-mac-swift).
