### ISSUE TITLE
New update of Pock won't run on Big Sur 11.5.2

### ISSUE THREAD

**Issue by jrocios** [pock/pock#518]
**Describe the bug**
For some reason it stopped working on my mbp 16 ever since I updated to the latest release of Pock. After clicking the app, it would appear on the menu bar and would immediately disappear. I have tried restarting the system, checking the security and privacy of preferences, and reinstalling the Pock app. All options were unviable. 

**How to reproduce**
```
1. Click on the Pock App 
2. Appears on Menu Bar
3. Immediately dissappears. 
4. Error
```

**Expected behavior**
Before updating to the latest release, it has worked perfectly fine. Clicking on the Pock itself would just run flawlessly. 

**Screenshots**
https://user-images.githubusercontent.com/87358913/132522690-7968dc6b-f942-4288-b9b5-748fa5edd6e6.mov

**Crashlog**
[User Report Pock Crash.zip](https://github.com/pock/pock/files/7129303/User.Report.Pock.Crash.zip)

**Versions:**
 - macOS version: Big Sur 11.5.2 
 - Pock version:  0.9.0-22

**Additional context**

**Comment by YakShavingCatHerder** [comment]
@jrocios I ran into a similar issue where Pock would either crash or load bricked modules.

Versions:
- macOS Big Sur 11.5.2 (Intel)
- Pock 0.9.0-22

I was able to get a working build after a thorough cleanse.

1. Clear your settings
- System Preferences -> Security & Privacy -> Privacy tab -> uncheck Pock everywhere (Accessibility, Full Disk Access, Screen Recording)

2.  Trash all currently installed/downloaded versions of Pock

3.  Clear all Pock settings and caches. This one liner will find all Pock related files and delete them for you:
`sudo find ~/Library ~/Applications /System/Volumes/Data /private/var/folders -iname *.pock* -print0 -print 2>/dev/null -exec sh -c 'echo Pock file found..."\n"; sudo rm -rf "${0}"; echo Pock file deleted at "${0}"' {} \; && sudo find ~/Library ~/Applications ~/System /System/Volumes/Data /private/var/folders -iname *.pock*
`

After these steps, I re-downloaded current .zip and installed default widgets via the Touch Bar prompt. Stable for almost a day now.

**Comment by bryan-ash** [comment]
YakShavingCatHerder's advice seems to be working for me 👍

I did need to quote `"*.pock*"` in step 3 for zsh to accept it
