### ISSUE TITLE
[Now playing widget] Invert swipe gesture is always enabled

### ISSUE THREAD

**Issue by evgen66rus** [pock/pock#520]
Once you untick the "Invert swipe gesture" option, it appears to be ticked again if you switch to another widget settings and get back.
Also, there is no option to hardcode a player. For example, I'm listening to spotify and launching a video on youtube.. wanna stop spotify, but there is Firefox browser already on the widget, even though they are playing both at the same time.

**Comment by SoloUnity** [comment]
For inverted swipe, you can force a change of it through pock's plist.

**Comment by jason-wihardja** [comment]
Just stumbled upon this myself, so for those who can't figure out the right command for this, here is what you should use
`defaults write com.pigigaldi.pock invertSwipeGesture -bool false`
