### ISSUE TITLE
Pock automatically hides the dock

### ISSUE THREAD

**Issue by lucacorbucci** [pock/pock#521]
**Describe the bug**
A clear description of what the bug is.

**How to reproduce**

1. Launch Pock, the dock disappears.
2. Turn Hiding off
3. Launch an app from the dock, the dock disappears again

**Screenshots**
I attach a video of what happens on my machine: https://app.iterspace.com/recording/f4b4544d-ac84-4d1d-b1bc-319a4eeb51d0

**Versions:**
 - macOS version: 11.4
 - Pock version:   0.9.0-22

**Comment by cade-rea** [comment]
This was frustrating me too! It looks like it is a widget setting:

Click Pock > Manage Widgets > Dock > Uncheck "Hide System Dock"
