### ISSUE TITLE
MacOS Monterey or older: The Dock widget disappeared after Lock screen

### ISSUE THREAD

**Issue by huyxgit** [pock/pock#529]
**Describe the bug**
This is supper annoying to me since I lock my screen pretty often when away, every time I log back in, the Dock widget gone, but the app still running. 

**How to reproduce**
```
1. Go to Apple logo -> 'Lock Screen'
2. Log back in
3. See error
```

**Versions:**
 - macOS version: 12.0.1 (Monterey)
 - Pock version:  0.9.0-22

**Comment by MarcusJr** [comment]
same issue

**Comment by Summer10** [comment]
Same here

**Comment by bluerxing** [comment]
A compromise approach is to double click ctr key when it unexpectly switch to default layout.

By my painful test:
1. when logout and login in short time. Mac os will reset touchbar to the system dedault layout and Pock don't override system layout (however override with long time logout). 

2. It also encounter this situation is unintentionally double click ctr key.

So getting used to Pock' function that double press ctr key to switch system layout and pock layout.

**Comment by bluerxing** [comment]
A compromise approach is to double click ctr key when it unexpectly switch to default layout.

By my painful test:

when logout and login in short time. Mac os will reset touchbar to the system dedault layout and Pock don't override system layout (however override with long time logout and login).

It also encounter this situation when unintentionally double click ctr key.

So getting used to Pock' function that double press ctr key to switch system layout and pock layout.
