### ISSUE TITLE
Catalina Required Error

### ISSUE THREAD

**Issue by maxoakland** [pock/pock#533]
**Describe the bug**
The main download link, which the website says works with 10.13 and above, will not open on a Mac with 10.14. It says 10.15 is required
**How to reproduce**
```
1. Download on a Mac with Mojave, open the zip file
2. See error
```

**Expected behavior**
It says it works on 10.13 and above

**Screenshots**
![image](https://user-images.githubusercontent.com/57502156/139957615-6dd35429-d010-430d-b15a-6acf1fd33368.png)

**Versions:**
 - macOS version: 10.14.6
 - Pock version:  .9.0.22

**Additional context**
Downloaded with Chrome

**Comment by Doregon** [comment]
<img width="250" alt="Screen Shot 2022-01-09 at 23 02 29" src="https://user-images.githubusercontent.com/55281754/148717195-542dce43-b15b-45cd-9c1c-b605e5bdd7c1.png">
