### ISSUE TITLE
Add a function keys widget to customise which ones desired

### ISSUE THREAD

**Issue by paddyroddy** [pock/pock#536]
**Describe the feature you'd like to have in Pock**
For as long as I've had a mac, I've always had a hotkey window in `iterm2` which I have bound to `F1`. Prior to learning about `pock` I would therefore have the touch bar show function keys as default, and on long `fn` press show the control strip. What I would like is the ability to just add say `F1` to my custom `pock` layout.

**Describe alternatives you've considered**
For now, I'm having it default to the function keys and only see the pock view on long `fn` press.

**Comment by cryocaustik** [comment]
agreed that this would be extremely helpful; having the ability to had a few fn keys you need or toggle the full array of fn keys would be great.
