### ISSUE TITLE
ESC key missing

### ISSUE THREAD

**Issue by Oclair** [pock/pock#537]
Hey there,

One day poof, ESC key missing, Pock useless.
Quitting Pock returns the ESC key to it's rightful location.

Been using Pock for years.
Have a nice day.

**Describe the bug**
A clear description of what the bug is.

**How to reproduce**
```
1. Go to '...'
2. Click on '....'
3. Scroll to '....'
4. See error
```

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
`To take a Touch Bar screenshot use the shortcut "shift + cmd + 6"`

**Crashlog**
If applicable, add crashlog to help me investigate your problem.
``` 
1. Open the Console application located at "Application -> Utilities -> Console.app."
2. Click on "User Reports" in the left menu, then locate the latest Pock crash report. (You can filter reports by typging "pock" into the searchbar on the top)
3. "ctrl + click" on the latest Pock crash report and click on "Reveal in Finder" option, then attach the .crash file in this issue.
```

**Versions:**
 - macOS version: [e.g. 10.14.5 (*required)]
 - Pock version:  [e.g. 0.5.2   (*required)]

**Additional context**

**Comment by Oclair** [comment]
imagine if folks downloaded the app and it included the latest widgets and didn't require giving the app "cloud Blanc"?

**Comment by sebastiantf** [comment]
Esc key is missing for me
