### ISSUE TITLE
More Mouse Input

### ISSUE THREAD

**Issue by DharmikSPatel** [pock/pock#538]
**Feature Request**

Currently, the Dock Widget can be interacted with by touch and by mouse. But the other widgets can **only** be interacted with by touch. I request that you implement the following features:
**Now Playing Widget**
User should be able to click the pause/next/prev buttons with their mouse. Also, if the user swipes with 2 fingers on trackpad when the cursor of the mouse is on the Now Playing Widget, then the track so go to the next track or track should go to the prev track depending on the gesture.

**Control Center Widget**
User should be able to click the volume up, volume down, brightness up, brightness down, mute buttons with mouse as well.

Thank You, I love using Pock

**Comment by pigigaldi** [comment]
Working on this 👍🏻

**Comment by samblooms** [comment]
@pigigaldi 
> Working on this 👍🏻

Awesome. Love to see active development again.
Some more mouse features would definitely be a welcome addition. App expose is sooooo close to solving my needs, Just need to be able to access it via the Mouse.

ATM, app expose seems to only activate via "Scrubber Long Press". Doesn't seem to detect short vs long clicks with "Mouse Click".

Great to have you back and I'm looking forward to coming improvements!

**Comment by pigigaldi** [comment]
Thanks for your feedback! 
The App Exposé controller in the Dock Widget only supports short-click ATM. If you tap/click on the active window for the frontmost application (indicated by a blue label) the window will be minimized. Just tap on the minimized window's tile to bring it up again.

**Comment by samblooms** [comment]
Interesting. Currently, with strictly mouse input, I can only bring a given application to the front. No minimize.
If I actually touch an application, I can do the same with no minimization, but a long press with touch does allow me to quit
application or show all of the windows of that application.

(Monterey 12.1 on the MacBook Pro 16,1)
