### ISSUE TITLE
Three bar wifi icon

### ISSUE THREAD

**Issue by sealvessel** [pock/pock#539]
**Describe alternatives you've considered**
None

**Additional context**
Make the wifi strenght indicator in the touchbar three bars, not four by default. There can be an optin for people who are used to the 4, but overall 3 is better. 4 is hideous and I can't take my eyes off the non-apple touchbar icon.

**Comment by Doregon** [comment]
I would +1 this and say to use SF Symbols, but those debuted with macOS Big Sur, so getting an Apple-like icon would require designing your own or bumping the minimum version to macOS 11 (or adding some if statements).
