### ISSUE TITLE
Adding the Dock widget causes Pock to immediately crash, unable to re-open

### ISSUE THREAD

**Issue by AndrewHocking** [pock/pock#541]
**Describe the bug**
Adding the Dock widget causes Pock to immediately crash. After this, Pock will not relaunch at all, even after a reboot. The only solution is to uninstall Pock entirely, re-install it, and not use the Dock widget. Adding the Dock widget again will cause the same issue even after a re-install. It does not seem to matter what other widgets are in the Touch Bar. The issue occurs when the Dock is the only widget added, and when every widget is added.

**How to reproduce**

1. Open the "Customize Pock" menu
2. Add the Dock widget to the Touch Bar
3. Click or tap "Done"
4. Pock will crash, never to open again

[Video demonstration of issue](https://youtu.be/zVuYi6LPSQM)

**Expected behavior**
The Dock widget is added to the Touch Bar.

**Crashlog**
[Crash_Reports.zip](https://github.com/pock/pock/files/7598125/Crash_Reports.zip)

**Versions:**
 - macOS version: 11.2
 - Pock version:  0.9.0-22

**Additional context**
I only began having this problem after updating from Pock to Pock 2. However, even after fully uninstalling both and reinstalling Pock 2, the problem persists, so I'm not sure if that's related.

**Comment by tmaleckiplacester** [comment]
I have the same problem on M1 Macbook Pro. Started with version 0.9.0-22

**Comment by pigigaldi** [comment]
Do you still face this issue with the latest Dock Widget version? (2.0.4)

**Comment by AndrewHocking** [comment]
Just tried the latest Dock Widget version and the issue seems to be fixed for me! :)

**Comment by pigigaldi** [comment]
> Just tried the latest Dock Widget version and the issue seems to be fixed for me! :)

Great! If the problem persists, please feel free to re-open :)
