### ISSUE TITLE
Cursor support stopping to work now and then

### ISSUE THREAD

**Issue by kulttuuri** [pock/pock#542]
**Describe the bug**
I have enabled the **cursor support** feature for the Pock app. It works well for some time but after a certain time using my Mac, it stops working, so can no longer move the cursor inside the Pock touch bar app. Will need to restart Pock or toggle the cursor support feature to get it working again.

**How to reproduce**
Use your mac for some time, switch between the apps.

**Expected behavior**
This function to be working and not stopping to work.

**Screenshots**
-

**Crashlog**
-

**Versions:**
 - macOS version: 11.6
 - Pock version: 0.9.0-22

**Additional context**
-

**Comment by pigigaldi** [comment]
Working on this 👍🏻

**Comment by pankaj9296** [comment]
Facing the same issue.
