### ISSUE TITLE
Disable double click control button to switch to debault Touch bar

### ISSUE THREAD

**Issue by eduardrudko** [pock/pock#543]
**Describe the feature you'd like to have in Pock**
I want to be able to turn off behavour when i double click control button pock switch to default Touch Bar

**Describe alternatives you've considered**

**Additional context**
If anyone passing by know how to disable this please leave comment below

**Comment by eduardrudko** [comment]
Bump, i think i am not the only one who would take enjoy of having this.

**Comment by Andrei-Aksionov** [comment]
It's indeed annoying. 
In my case I have a lot of keybindings that uses Ctrl modificator (in VSCode/Vim) and touchbar is constantly switching between built-in and Pock.

For example if I am in VSCode and want to open terminal and run the last entered command I do:
1. Ctrl+` - to open terminal
2. Ctrl+p - to select previous command

The expected delay for double press is too small and as a result default touch bar is selected.  

Would be nice if someone fixes it.
It might be possibility to switch off double ctrl, or make delay between double press much much smaller or ability to assign double press to another key.
