### ISSUE TITLE
This is about traching area

### ISSUE THREAD

**Issue by zxssss** [pock/pock#546]
first I think that pock app is most beter app,but when I used I find for an problem ,Questions are as follows
1.The length of the Touch Bar is not equal to the actual size of the tracking area, I hope to add the size adjustment option for the tracking area
2.It’s too slow when using the trackpad to scroll the "dock" widgets, I hope it can increase the speed of the trackpad when scrolling the "dock"
last I am a Chinese in China, so I may not be good at communicating in English, so there may be some spelling of words, or the usage is not clear. Please forgive me.
The above are all my suggestions and questions, I hope the author can see it, thanks！！

**Comment by zxssss** [comment]
my macbook pro was mbp13.3 m1 2020

**Comment by sarashino** [comment]
I agree with this request, especially former one.
BTW, pock app is the best.

**Comment by thelou1s** [comment]
me too, the tracking area adjustmentment! both width and height. thank you
