### ISSUE TITLE
Pock Dock Widget 2.0 v1 - "Duplicating" issue

### ISSUE THREAD

**Issue by Doregon** [pock/pock#547]
**Describe the bug**
When opening an app that isn't running, the Dock briefly shows the normal touch bar, then snaps back and now the pinned icons section has multiplied. Will attach recorded video separately.

**How to reproduce**
```
1. See above.
```

**Expected behavior**
The Dock doesn't multiply.

**Screenshots**

<img width="1085" alt="Touch Bar Shot 2022-01-09 at 23 08 02" src="https://user-images.githubusercontent.com/55281754/148717487-4e4b732b-8ed7-4bec-9ef3-be45e0637b52.png">

**Crashlog**
If applicable, add crashlog to help me investigate your problem.
``` 
N/A
```

**Versions:**
 - macOS version: 12.2 beta 1
 - Pock version:  0.9.22
 - Mac: MacBook Pro (15-inch, 2018)

**Additional context**
N/A

**Comment by devilending** [comment]
same bug with me

**Comment by c0rinne** [comment]
My dock is now showing 3 instances of the same apps.

**Comment by pigigaldi** [comment]
Got it 👍🏻 
While working on the fix, you can still downgrade to the previous version using the `"Advanced > Re-Install default widgets"` menu option :)

**Comment by c0rinne** [comment]
> Got it 👍🏻 ~While working on the fix,~ you can still downgrade to the previous version using the `"Advanced > Re-Install default widgets"` menu option :)
> 
> Update: A new version is available through the Widgets Manager panel. Let me know if you still face this issue.

Looks like the update works for me.

**Comment by Doregon** [comment]
Issue is now resolved with the latest version!
