### ISSUE TITLE
Dock widget: should not display "running" indicator when "Show only running apps" is enabled

### ISSUE THREAD

**Issue by ogerardin** [pock/pock#548]
**Describe the bug**
In previous version of the Dock widget (1.4 I believe), behaviour was correct. After update to 2.0, running indicator is displayed even when "Show only running apps" is enabled.

**How to reproduce**
Manage Widgets / Dock / check "Show only running apps".

**Expected behavior**
Since only running apps are displayed, running indicator should not be displayed.

**Screenshots**
<img width="1085" alt="Touch Bar Shot 2022-01-10 at 18 07 08" src="https://user-images.githubusercontent.com/110559/148807736-35f72393-98e8-46b2-8723-94500207d8df.png">

**Versions:**
 - macOS version: 10.15.7
 - Pock version:  0.9.0-22
 - Doc widget: 2.0

**Comment by pigigaldi** [comment]
Dock Widget 2.0 now follows System Dock Preferences for showing/hiding running indicators.
You can disable it there, if you prefer :)

**Comment by ogerardin** [comment]
> Dock Widget 2.0 now follows System Dock Preferences for showing/hiding running indicators. You can disable it there, if you prefer :)

Sorry but I think it shouldn't be the same setting: in the normal dock I want to display the running indicator because there are many icons and it makes sense to know which apps are running. But in Pock when I have selected "Show only running apps" there are only running apps in the touch bar so it makes no sense to show the running indicator!

Sharing the setting with the native dock is not an improvement, they are different docks and one should be able to use different settings. Or follow my advice and ignore the setting when "Show only running apps" is active :)

**Comment by ogerardin** [comment]
Did you implement this in Dock widget 2.0.1 ? It looks ok to me now :)
