### ISSUE TITLE
Ability to Toggle True Tone

### ISSUE THREAD

**Issue by FeistyFinn** [pock/pock#55]
Toggling true tone on and off is a pain for me when want to do colour critical stuff. This will be a useful feature to have.

**Comment by iDjay** [comment]
+ Dark Mode if possible :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lorenzofanchi** [comment]
use [Shifty](https://github.com/thompsonate/Shifty) 👍
