### ISSUE TITLE
Dock Widget 2.0 - App Icons bouncing for no reason

### ISSUE THREAD

**Issue by crystall1nedev** [pock/pock#550]
**Describe the bug**
When you start Pock, some of the app icons can bounce even if they are not open, in the process of opening, or asking for your attention.

**How to reproduce**
```
1. See above
```

**Expected behavior**
All of the icons are sitting patiently.

**Screenshots**
<img width="1085" alt="Touch Bar Shot 2022-01-12 at 13 09 34" src="https://user-images.githubusercontent.com/55281754/149197676-74dede02-3c12-4486-b633-b2d9b09b0dc4.png">

**Crashlog**
If applicable, add crashlog to help me investigate your problem.
``` 
N/A
```

**Versions:**
 - macOS version: 12.2 beta 1
 - Pock version:  0.9.22
 - Model: MacBook Pro (15-inch, 2018)

**Additional context**
N/A

**Comment by benjamimo1** [comment]
Same thing here. MacBook Pro M1, started happening after latest update.
Mac Os Monterrey 12.1 21C52
