### ISSUE TITLE
Dock widget: Unequal 'item spacing' when set to ≲ 3

### ISSUE THREAD

**Issue by oweneric** [pock/pock#551]
### **Environment**
macOS Catalina 10.15.7
Pock 0.9.0-22
Dock 2.0.4 (Pock widget)

### **Description of minor bug**

When 'item spacing' in 'Dock' widget settings is set to 3 or less, the vertical line space between 'folders/stacks + Trash' section and 'recent apps' section is wider than the vertical line space between 'dock apps' section and 'recent apps' section.

The lower the 'item spacing' setting number, the bigger the difference between the two spacings.

I use 'item spacing' of -7, where the difference is spacing is particularly noticeable.

When I was on Dock v1.x, I was using 'item spacing' of -10, so very close together, but still spaced out. However, an 'item spacing of ≲ -10 now on v2.0.4 causes neighboring icons of 'dock apps' and 'recent apps' to overlap.

### **How to refresh 'item spacing' setting**
Click on another widget tab in 'Widgets Manager' for dock in touch bar to reflect a new 'item spacing' number set in 'Dock' widget settings.

### **Expected behavior**
- Item spacing to be equal throughout Dock widget icons to reflect single 'item spacing' number in 'Dock' widget settings.
- Item spacing of 0 to mean icons are touching. Item spacing < 0 to mean overlapping icons.
- Minor extra feature of being able to set vertical line spacing between Dock sections and normal icon spacing independently.

### **Screenshots**
[Side note: I have selected 'Hide Trash' in my 'Dock' widget settings, and so the 'Trash' icon does not appear in my touch bar.]

- **'Item spacing' = -7**
<img width="1004" alt="Touch Bar Shot 2022-01-16 at 9 00 50 AM" src="https://user-images.githubusercontent.com/57324248/149643329-9da3d82e-ee47-4e72-b361-b21b3a3e6b63.png">

- **'Item spacing' = -10**
<img width="1004" alt="Touch Bar Shot 2022-01-16 at 9 01 53 AM" src="https://user-images.githubusercontent.com/57324248/149643333-2315ec1e-389d-4464-be6c-011187963234.png">

- **'Item spacing' = -15**
<img width="1004" alt="Touch Bar Shot 2022-01-16 at 9 03 08 AM" src="https://user-images.githubusercontent.com/57324248/149643353-f0cd7223-aad6-4f71-a8b8-c23175e43e18.png">

**Comment by basmets6** [comment]
+1 on this. Noticed it as well, primarily from the first icon on the left. Then it's fine.
