### ISSUE TITLE
Double control does not return to default touch bar

### ISSUE THREAD

**Issue by Wouter-VDP** [pock/pock#552]
**Describe the bug**
When I press control twice, nothing is happening.
In the preferences, "Default Touch Bar shows" is set to App.

**How to reproduce**
Probably after installing macOS Monterey

**Versions:**
 - macOS version: Monterey 12.1
 - Pock version:  0.9.0-22

**Comment by pigigaldi** [comment]
Can you please try again and be sure that Pock is not the frontmost window on the desktop?

**Comment by Wouter-VDP** [comment]
Hello,
I did check this, however, if I first pressed ctrl+CMD and then double
ctrl, the functionality was restored.
If I figure out anything more useful, I'll let you know.

Thank you for the continued development!
Wouter

**Comment by kylegorter** [comment]
I've just restored Monterey to defaults and had you problem. I solved by changing the dictation key to something else.
