### ISSUE TITLE
Pock stop working when update Dock widget to 2.0.7

### ISSUE THREAD

**Issue by VictorKleist** [pock/pock#554]
Pock stop working when Dock is updated from 1.4 to 2.0.7

Received a notification about a new dock version, but the software stop responding after updated. I do receive the message saying it was update and need to relaunch, after that it stop responding
If I close the app using Active Monitor and start it again, it already opens froze

I've uninstalled Pock using AppCleaner and tried to update from a new installation, but happened the same after Dock update 

    macOS version: Big Sur 11.6.2 (20G314)
    Pock version: 0.9.0.22-2

**Comment by VictorKleist** [comment]
My current setup in case it help in something, also there wasnt any log do upload
<img width="1004" alt="Captura da Touch Bar 2022-01-24 às 13 32 08" src="https://user-images.githubusercontent.com/22733917/150824205-45852b2b-1ecb-41a5-85cb-4075028d6b13.png">

**Comment by pigigaldi** [comment]
Can you please share a screenshot of the real Dock? Just to check if any elements could lead the Dock widget to a crash. Thanks!

**Comment by yrylalala** [comment]
I also encountered the same problem.
<img width="1004" alt="触控栏快照2022-02-01 16 42 14" src="https://user-images.githubusercontent.com/29858901/151937738-55850413-aca9-4c49-b6d7-d3fe4e86a2cd.png">

```
macOS version: macOS Catalina 10.15.7 (19H1713)
Pock version: 0.9.0-22 Dock 2.0.7
```

**Comment by VictorKleist** [comment]
I've tried to reinstall BigSur but the issue has persisted. But now that i've upgrade to Monterrey it's working normal. 
As requested, here is my current dock, i dont use any other uncommon apps that could crash Pock 

The issue is resolved for me 

<img width="1361" alt="Captura de Tela 2022-02-01 às 08 46 10" src="https://user-images.githubusercontent.com/22733917/151964337-ba43134a-debd-4600-be43-4f6782264b8d.png">

**Comment by Mobu002** [comment]
My pock has lost its dock component and I can't choose to show the application icon when personalising it.

**Comment by Mobu002** [comment]
<img width="1004" alt="触控栏快照2022-02-04 下午3 15 53" src="https://user-images.githubusercontent.com/99007320/152487609-12c7c1f8-8c40-4641-9edc-cd7bc70b3ab8.png">
<img width="1285" alt="截屏2022-02-04 下午3 16 40" src="https://user-images.githubusercontent.com/99007320/152487695-19db9bf5-c38f-4197-978d-294aebe71f85.png">

How can I solve this problem please? I am very troubled by the loss of this feature.
