### ISSUE TITLE
Pock 2 just asked for permission to access external drives.

### ISSUE THREAD

**Issue by entozoon** [pock/pock#556]
Pock 2 just asked for permission to access external drives.
That seems a little suspicious? I can't imagine why it'd require that.

**Comment by pigigaldi** [comment]
The Dock widget can be used to navigate folders as Finder does. Obviously, if you try to navigate to an external drive, it'll ask for your permission :)

**Comment by entozoon** [comment]
It did that without any navigation or interaction at all but fair enough!
