### ISSUE TITLE
Bring Back "Hide Running Indicator"

### ISSUE THREAD

**Issue by andiapar** [pock/pock#559]
The newest update of Pock has removed the option to 'Hide Running Indicator' under the "Dock" preferences. 

Please bring this option back, as some of us prefer the larger icons for easier usability when touching the icons with fingers + navigating the icons with the mouse via the Touch Bar. I use my fingers to task-switch all day long, and have already hit the wrong icons multiple times today.

PLEASE CONSIDER - I am a long-time Pock user but I regret downloading the newest version due to this (1) singular update. Super bummed.

**Comment by pigigaldi** [comment]
The Dock Widget now reads the system Dock preferences relative to the running indicator to know if it should show the indicator or not.
