### ISSUE TITLE
"Launch at login" box keep unchecking and not launching at login

### ISSUE THREAD

**Issue by 3LL10TR022** [pock/pock#563]
1. Go to 'Preferences'
2. Click on 'Launch at login'
3. 'logout / resart'
4. fails to open and when going back into the preferences tab the "Launch at login" box is unchecked.
```

**Versions:**
 - macOS version: 12.2.1 
 - Pock version: 0.9.0-22

**Comment by EmpDns** [comment]
Having this issue also.

**Comment by Radixtrator** [comment]
I have the same issue to its definitely not resolved..
