### ISSUE TITLE
Control Centre widget doesn't work.. Standard Control Strip remains

### ISSUE THREAD

**Issue by basmets6** [pock/pock#571]
**Describe the bug**
Just reinstalled Pock. Upon reinstalling, everything works very very well, except for the Control Centre area. Usually it'll show up and replace the standard Control Strip from MacOS. Now, I just keep getting the standard MacOS Control Strip. I can't get it to go away. All the other widgets seem to be working..

**Expected behavior**
Control Centre widget replaces the Control Strip from MacOS

**Screenshots**
https://imgur.com/a/6CnruPA

**Crashlog**
Unfortunately there's no crash log.. Just isn't acting the way it should

**Versions:**
 - macOS version: 12.3.1
 - Pock version: 0.9.0-22

**Comment by pigigaldi** [comment]
Hi! Make sure to have the "Full width" layout selected in Pock's preferences.
<img src="https://pock.app/_nuxt/img/preference_general.f5f55b1.png" width="500">
