### ISSUE TITLE
Feature Request to Be Able To Switch to App Controls when using Apps like Safari or Chrome or Spotify

### ISSUE THREAD

**Issue by KushinP** [pock/pock#572]
There needs to be a way for Pock to either automatically or have a button to switch between the pock layout on the touch bar and the native App Controls on the touch bar. This si very necessary because in apps like Spotify and Safari a lot of the controls are embedded there and then you lose a lot of the functionality which isn't great. One way of solving this would ideally be a button where you can engage or disengage Pock from the touch bar so then if you wish to use the native app controls or you can continue using pock.

**Comment by pigigaldi** [comment]
Pock already has this capability. You can double press the `control` key to switch between Pock's layout and the default Touch Bar controls.
