### ISSUE TITLE
Right click menu

### ISSUE THREAD

**Issue by yuha0** [pock/pock#75]
**Is your feature request related to a problem? Please describe.**
So first, thank you for the fantastic work. For me, Pock is just one step away from fully replacing the dock: I need app's right click menu so that I can 1) force kill an app. 2) use some app specific feature like "open new incognito window in Chrome".

**Describe the solution you'd like**
A gesture to open the right click menu in the touch bar. Maybe a long pressing on an icon?

**Comment by antwan** [comment]
+1, this is the only thing missing so it can really replace the dock. This is a must have.

**Comment by JamesAscroft** [comment]
Absolute must have. Please make this a priority!

**Comment by Y-H-Joe** [comment]
yes I agree.
