### ISSUE TITLE
Pock does not update when dock items are re-ordered

### ISSUE THREAD

**Issue by davidcelis** [pock/pock#80]
**Describe the bug**

After re-ordering items in my dock, Pock will continue to display the old dock item ordering. This unfortunately seems to persist through quitting and restarting Pock.

**To Reproduce**

1. Open Pock
2. Move one or more items in the dock to a new position
3. Look at Touch Bar, see that the re-ordering is not reflected

**Expected behavior**

Pock always displays items in the same order as the dock

**Screenshots**

Dock:

![dock](https://davidcelis.nyc3.cdn.digitaloceanspaces.com/screens/Screen-Shot-2019-06-20-10-38-26.44.png)

Touch Bar:

![touch bar](https://davidcelis.nyc3.cdn.digitaloceanspaces.com/screens/Touch-Bar-Shot-2019-06-20-at-10.39.09-AM.png)

**Desktop (please complete the following information):**

 - macOS 10.14.5
 - Pock 0.4.6

**Comment by pigigaldi** [comment]
I'm closing this. Let me know if you're facing this issue also in 0.5.1

**Comment by davidcelis** [comment]
@pigigaldi I updated to 0.5.1 and when Pock re-opened, all of the touch bar items were still in the incorrect order based on my dock

**Comment by pigigaldi** [comment]
Thanks! I’ll look into this

**Comment by iDjay** [comment]
it's the same when you open an app which isn't the dock:
1. open an app which is not in the dock
2. the app launches, is visible in Dock but not in Pock 
- for some reasons this only happens with a few apps (MacUpdater, Splice f.e.)

**Comment by iDjay** [comment]
I also noticed that apps which launch at start (AdGuard in my case) won‘t disappear from Pock after closing. Restarting Pock fixes the
Issue. @pigigaldi 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
![MacUpdater not visible in Pock by iDjay](https://i.imgur.com/vGHpQ1r.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MateuszDabrowski** [comment]
For me, the order of items in pock never was the same as the order in the dock. Reordering the dock changes nothing. Restarting the Pock changes nothing.

**Comment by EvyBongers** [comment]
+1 on this.

It seems that Pock shows icons in most recently launched order. I get that this may be by design, but I would prefer if the order is the same as on my ribbon. Maybe add an option to choose either of these modes?

**Comment by dalmaer** [comment]
+1

I get this with 0.7.2 on Catalina. Didn't used too. The order doesn't seem to be recent for me, but as I add new items to the dock they are always appended to the end of the touchbar list even if they are on the left on the dock itself.
