### ISSUE TITLE
Indicators for Open Apps

### ISSUE THREAD

**Issue by ccadieux** [pock/pock#81]
**Is your feature request related to a problem? Please describe.**
Always shows indicators for open apps. 

**Describe the solution you'd like**
It would be nice to have a preference to turn off indicators for open apps like you can on the dock. 

**Describe alternatives you've considered**
N/A

**Additional context**
The way I use my dock is to remove everything and use spotlight to launch apps. Only running apps show on my dock. The app indicator is useless info for me since all the apps are running. Removing the indicator would also let the icon be bigger.

**Comment by pigigaldi** [comment]
Thanks for pointing this out, I'm going to implement this in a future release 👍

**Comment by lorenzofanchi** [comment]
bigger icons = better ;)

**Comment by Einkoro** [comment]
Rather than making this its own option wouldn't it make more sense to hide the indicators when the "Show only running apps" option is checked?
