### ISSUE TITLE
"Show only running apps" changes sort order

### ISSUE THREAD

**Issue by lorenzofanchi** [pock/pock#91]
**Describe the bug**
When enabling the "Show only running apps" option, the sort order of the Touch bar dock items is different from the order in the Dock

**To Reproduce**
1. Go to Preferences
2. Enable "Show only running apps"
4. Order of apps changes in Touch bar and doesn't reflect order in Dock

**Expected behavior**
The order of the icons in the Touch bar should be the same as in the Dock, only omitting the apps that are not currently running

**Screenshots**
Before option (order shown is as in Dock):
<img width="1085" alt="Touch Bar Shot 2019-06-23 at 15 28 45" src="https://user-images.githubusercontent.com/770285/59976958-b212ff80-95cb-11e9-9a4e-1e29528d1de5.png">

After option (note Slack icon shifted):
<img width="1085" alt="Touch Bar Shot 2019-06-23 at 15 28 50" src="https://user-images.githubusercontent.com/770285/59976960-b6d7b380-95cb-11e9-9556-73394b892548.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Pock: 0.5.1

**Comment by pigigaldi** [comment]
That’s not what you asked for in #63
Maybe I didn’t understand the other request, so can you please explain in detail what would be your desired behavior?
Thanks!

**Comment by lorenzofanchi** [comment]
No, indeed the two are different :)

"Show only running apps" would prevent any apps that are not running from showing up in Pock, but the _order_ of the running apps would match what you see in the Dock.

"Sort by recent use" would be a sub-option of "Show only running apps", where only running apps are shown, but they are _sorted in order of most recent use_

Let me know if this clears it up! If not, I can provide some mockups of each behavior :)

**Comment by randallsquared** [comment]
It seems to me that there are two separate features, here.   

1. a toggle to order apps by most recent use
2. a toggle to show only apps that are currently running

What surprised me when I first tried Pock today, and what I imagine surprised @lorenzofanchi , was that there's no way to show only apps that are currently running, but in the same order they would be shown in the dock.

I don't know if Pock has access to the dock preferences toggle "Show recent applications in Dock", but if so, feature 2 above could be implemented by obeying the built-in Dock preferences, and the "Show only running apps" toggle in Pock Preferences could be changed to "Order apps by most recent use".

Thanks for Pock!

**Comment by MateuszDabrowski** [comment]
Ahoj @lorenzofanchi , @pigigaldi ,
From my tests, it looks like indeed the preference of mirroring the dock preserves the order in the dock, but preference to show only launched apps shows those apps in order of first launching (the launching when the Mac was powered on and the app was for the first time opened, not last use).

**Comment by Jobey-G** [comment]
> That’s not what you asked for in #63
> Maybe I didn’t understand the other request, so can you please explain in detail what would be your desired behavior?
> Thanks!

Thanks for Pock **pigigaldi**, I think what **lorenzofanchi** is saying is that the order of open (active) apps on the Touch Bar mirrors the order on the dock. See screenshot below. You can see Messages comes up first even though it is fourth on the dock—not including the Finder as I have that hidden.

![Pock-Dock](https://user-images.githubusercontent.com/57012598/71739787-509bdb00-2e0f-11ea-9e5b-8b2070c04feb.jpg)

**Comment by Kayne** [comment]
> You can see Messages comes up first even though it is fourth on the dock—not including the Finder as I have that hidden.

I think you meant Safari not Messages. :)

I have exactly the same issue with apps. I configured Pock to display just running apps but their order is completely different than apps in my dock and I'm confused. I am very used to the order of my apps in Dock so I can't use Pock - it takes too much time to find the correct app on TouchBar because it's always in the wrong place (in comparison to my Dock).

**Comment by Jobey-G** [comment]
> I think you meant Safari not Messages. :)

Nope, I meant Messages, key word is "active". It's first in Pock but fourth on my Mac Dock not including Finder as I have that unselected in Pock preferences. Nonetheless, Pock doesn't mirror the active apps in my Dock. Would be dope if it did.

**Comment by sethperfecthat** [comment]
I feel exactly the same. I'd much prefer to show "only running apps" because of space on the touchbar, I dont want to have to swipe over to see hidden apps....but when I turn on "show only running apps" the order does switch to "first opened as first, and so on" which causes a similar issue as @Kayne has mentioned in that it throws off my workflow.

**Comment by jaredtkatz** [comment]
The ability to sort applications by most recent use (a la ⌘+⇥) would be great.

**Comment by evgen66rus** [comment]
Finder is not included to "Show only running apps" option. If I enable the option, there is no Finder in the touch bar ("Hide Finder" is disabled)
