### ISSUE TITLE
Pock ribbon not expanding on touching the Pock Icon in the strip

### ISSUE THREAD

**Issue by TechieGenie** [pock/pock#96]
I am unable to expand the Pock Ribbon on touching the `Pock` icon in the strip. Only Double pressing <kbd>control</kbd> works.

**Comment by pigigaldi** [comment]
Thanks for pointing this out, I'll take a look asap!

**Comment by TechieGenie** [comment]
@pigigaldi I can see 2 <kbd>esc</kbd> buttons on the strip when I open the pock preferences and also after closing the window. The close button is invisible until I double press <kbd>control</kbd>. I can raise a separate bug in case this is not the right way to bring to ur notice :)

**Comment by pigigaldi** [comment]
> @pigigaldi I can see 2 esc buttons on the strip when I open the pock preferences and also after closing the window. The close button is invisible until I double press control. I can raise a separate bug in case this is not the right way to bring to ur notice :)

Explanation of this can be found here https://github.com/pigigaldi/Pock/issues/94#issuecomment-504774806

**Comment by zijievv** [comment]
I also have this issue. And it shows two `esc` buttons.

**Comment by arashsa** [comment]
I am also experiencing this issue. The pock icon is visible, but nothing happens when I click it.

**Comment by purkkis** [comment]
I also had this issue right after my first install of Pock but I was able to solve the issue by just quitting the app and launching it again.

**Comment by MateuszDabrowski** [comment]
Same issue for me - and also, just as @purkkis said, quitting pock and relaunching it solved the issue.
